/** Every fixed label in the "หนีหนู" interface, in both languages. */
import type { Loc } from './types';

export const UI = {
  back: { th: 'หมวดเกม', en: 'All games' },
  gameTitle: { th: 'หนีหนู', en: 'Off the Wheel' },
  gameSub: {
    th: 'เกมกระดานการเงินที่คุณชนะเมื่อเงินไหลเข้าต่อเดือน มากกว่ารายจ่ายต่อเดือน',
    en: 'A financial board game you win the month your passive income outgrows your expenses.',
  },
  rules: { th: 'กติกา', en: 'Rules' },
  restart: { th: 'เริ่มใหม่', en: 'New game' },
  close: { th: 'ปิด', en: 'Close' },

  /* setup */
  setupStep1: { th: '1. เลือกอาชีพ', en: '1. Pick a job' },
  setupStep2: { th: '2. เลือกความฝัน', en: '2. Pick a dream' },
  setupHint: {
    th: 'อาชีพกำหนดเงินเดือน รายจ่าย และหนี้ตั้งต้น ยิ่งเงินเดือนสูง รายจ่ายยิ่งสูงตาม เส้นชัยจึงไม่ได้อยู่ที่ใครเงินเดือนเยอะกว่า',
    en: 'The job sets your salary, expenses and starting debts. Higher salaries come with higher expenses, so the finish line is not about who earns more.',
  },
  dreamHint: {
    th: 'ความฝันคือเป้าหมายสำรองบนทางด่วน ซื้อได้เมื่อไหร่ก็ชนะทันที ราคาต่างกันเกือบเจ็ดเท่า เลือกฝันใหญ่แปลว่าเลือกเกมที่ยาวขึ้น',
    en: 'The dream is your alternate goal on the fast track: buy it and you win on the spot. They differ almost sevenfold in price, so a bigger dream is a longer game.',
  },
  startGame: { th: 'เริ่มเล่น', en: 'Start' },
  resume: { th: 'เล่นต่อจากเกมเดิม', en: 'Resume saved game' },
  salary: { th: 'เงินเดือน', en: 'Salary' },
  startCash: { th: 'เงินสดตั้งต้น', en: 'Starting cash' },
  startCf: { th: 'กระแสเงินสด', en: 'Cash flow' },
  escapeNeed: { th: 'ต้องหาเงินไหลเข้าให้ถึง', en: 'Passive income needed' },
  /** on a job card the escape bar and the expense line are the same number, so
      they share one row instead of being printed twice */
  expensesIsBar: { th: 'รายจ่าย = เส้นชัย', en: 'Expenses = the bar' },

  /* statement */
  statement: { th: 'งบการเงินของคุณ', en: 'Your financial statement' },
  income: { th: 'รายได้', en: 'Income' },
  passive: { th: 'เงินไหลเข้า (passive)', en: 'Passive income' },
  expenses: { th: 'รายจ่าย', en: 'Expenses' },
  taxes: { th: 'ภาษี', en: 'Taxes' },
  /* The tax breakdown popover. Thai personal income tax is charged by category,
     and which category your money arrives in is most of the answer. */
  taxWhyTitle: { th: 'ภาษีเดือนนี้คิดมาจากไหน', en: 'Where this month’s tax comes from' },
  taxWhyBody: {
    th: 'เงินก้อนเท่ากันเสียภาษีไม่เท่ากัน ขึ้นอยู่กับว่ามันมาจากไหน เงินเดือนหักค่าใช้จ่ายได้ครึ่งหนึ่งแต่ไม่เกินปีละ 100,000 ค่าเช่าหักเหมา 30% กิจการหักเหมา 60% สามอย่างนี้เอามารวมกันแล้วไต่ขั้นบันไดเดียวกัน ส่วนปันผลแยกไปจ่าย 10% จบในตัวเอง ไม่ขึ้นบันไดกับใคร',
    en: 'The same money is taxed differently depending on where it came from. A salary deducts half of itself, capped at ฿100,000 a year; rent deducts a flat 30%; a trade deducts a flat 60%. Those three are added together and climb one ladder. Dividends leave at a flat 10% and never join it.',
  },
  taxByCategory: { th: 'แยกตามประเภทเงินได้', en: 'By category of income' },
  taxCatHead: { th: 'ประเภท', en: 'Category' },
  taxGross: { th: 'รับเข้า', en: 'Received' },
  taxDeduct: { th: 'หักค่าใช้จ่าย', en: 'Deduction' },
  taxTaxable: { th: 'เหลือคิดภาษี', en: 'Taxable' },
  taxCatSalary: { th: 'เงินเดือน', en: 'Salary' },
  taxCatSalaryNote: { th: 'ประเภท 1 · หัก 50% ไม่เกินปีละ 100,000', en: 'type 1 · 50%, capped at ฿100,000 a year' },
  taxCatRent: { th: 'ค่าเช่า', en: 'Rent' },
  taxCatRentNote: { th: 'ประเภท 5 · หักเหมา 30%', en: 'type 5 · flat 30%' },
  taxCatBiz: { th: 'กิจการ', en: 'Trade' },
  taxCatBizNote: { th: 'ประเภท 8 · หักเหมา 60%', en: 'type 8 · flat 60%' },
  taxPerMonthNote: { th: 'ตัวเลขทั้งหมดหารเป็นต่อเดือนแล้ว ของจริงคิดกันเป็นรายปี', en: 'Every figure is shown per month; the real thing is assessed by the year.' },
  taxAllowance: { th: 'ค่าลดหย่อน (ส่วนตัว + บุตร)', en: 'Allowances (personal + children)' },
  taxNet: { th: 'เงินได้สุทธิ', en: 'Net taxable income' },
  taxLadder: { th: 'ขั้นบันไดภาษี', en: 'The ladder' },
  taxBand: { th: 'ช่วงเงินได้สุทธิต่อปี', en: 'Net income band, per year' },
  taxRate: { th: 'อัตรา', en: 'Rate' },
  taxInBand: { th: 'ของคุณอยู่ในช่วงนี้', en: 'Yours in this band' },
  taxOwed: { th: 'ภาษีช่วงนี้', en: 'Tax here' },
  taxNetBridge: { th: 'ตารางบนต่อเดือน · ขั้นบันไดคิดเป็นรายปี', en: 'table above is monthly; the ladder is annual' },
  taxYearNote: { th: 'ตารางนี้เป็นรายปีทั้งหมด เพราะกฎหมายเขียนเป็นรายปี', en: 'This whole table is annual, because that is how the law is written.' },
  taxMarginalNow: { th: 'บาทถัดไปของคุณโดน', en: 'Your next baht is taxed at' },
  taxFromLadder: { th: 'ภาษีจากขั้นบันได', en: 'Tax from the ladder' },
  taxDividend: { th: 'ภาษีปันผล', en: 'Dividend tax' },
  taxDividendNote: { th: 'หัก ณ ที่จ่าย 10% แล้วจบ ไม่เข้าขั้นบันได', en: 'withheld at 10% and settled there, off the ladder' },
  taxCorp: { th: 'ภาษีในนามนิติบุคคล', en: 'Tax inside the company' },
  taxTotalMonth: { th: 'รวมต่อเดือน', en: 'Total per month' },
  /* ---- the company: two pockets, and the price of moving between them ---- */
  corpTitle: { th: 'บริษัทของคุณ', en: 'Your company' },
  corpOpen: { th: 'จดบริษัท', en: 'Set up a company' },
  corpManage: { th: 'จัดการบริษัท', en: 'Manage the company' },
  corpSetupTitle: { th: 'ย้ายพอร์ตเข้าบริษัท คุ้มหรือยัง', en: 'Move the portfolio into a company?' },
  corpSetupBody: {
    th: 'บริษัทเสียภาษีของตัวเอง กำไรสามแสนแรกไม่เสียเลย ส่วนที่เกินไปถึงสามล้านเสีย 15% แทนที่จะไต่ขั้นบันไดส่วนตัวถึง 35% แต่มันมีค่าบัญชีทุกเดือนไม่ว่าจะมีกำไรหรือไม่ และเงินที่อยู่ในบริษัทยังไม่ใช่เงินของคุณ จะเอาออกมาใช้ต้องจ่ายภาษีอีกชั้น',
    en: 'A company is taxed on its own account: nothing on the first ฿300,000 of profit and 15% up to ฿3M, instead of climbing your personal ladder to 35%. It also pays an accountant every month whether it profits or not, and money inside it is not yours yet: taking it out is taxed again.',
  },
  corpSetupFee: { th: 'ค่าเข้าครั้งเดียว', en: 'One-off cost to get in' },
  corpSetupFeeNote: {
    th: 'ค่าจดทะเบียน บวกค่าธรรมเนียมโอนทรัพย์สินเข้าบริษัท 2% ของมูลค่า',
    en: 'registration, plus 2% transfer fees on everything moving across',
  },
  corpMoves: { th: 'ทรัพย์สินที่จะย้ายเข้าบริษัท', en: 'Holdings that move across' },
  corpMovesNone: { th: 'ยังไม่มีอสังหาหรือกิจการให้ย้าย', en: 'no property or business to move yet' },
  corpVerdict: { th: 'ต่างกันเดือนละ', en: 'Monthly difference' },
  corpVerdictNote: {
    th: 'คิดค่าบัญชี ภาษีนิติบุคคล และภาษีเงินเดือนกรรมการที่คุณถอนออกมาแล้ว',
    en: 'after the accountant, the company’s tax, and your tax on the salary you draw',
  },
  corpWorthIt: {
    th: 'ตอนนี้จดแล้วดีขึ้น เพราะพอร์ตโตพอจะกลบค่าบัญชีได้แล้ว แต่อย่าลืมว่ากำไรที่กองอยู่ในบริษัทยังต้องเสียภาษีอีกชั้นตอนถอนออกมา ภาษีที่ประหยัดได้คือภาษีที่เลื่อนออกไป ไม่ใช่ภาษีที่หายไป',
    en: 'Right now this comes out ahead: the portfolio is finally big enough to cover the accountant. Remember that the profit piling up inside is taxed again when you take it out. The tax you save here is deferred, not cancelled.',
  },
  corpNotYet: {
    th: 'ตอนนี้จดแล้วแย่ลง ค่าบัญชีแพงกว่าภาษีที่ประหยัดได้ นี่คือเหตุผลที่โครงสร้างซึ่งเหมาะกับคนตัวใหญ่กว่า เป็นแค่ค่าใช้จ่ายสำหรับคนตัวเล็กกว่า',
    en: 'Right now this comes out behind: the accountant costs more than the tax it saves. This is what it looks like when a structure built for someone bigger is simply an expense for you.',
  },
  corpDoIt: { th: 'จดบริษัทเลย', en: 'Register it' },
  corpDeskTitle: { th: 'คุณจะเอาเงินออกจากบริษัทยังไง', en: 'How do you get money out of the company?' },
  corpDeskBody: {
    th: 'มีสองทางและมันดึงกันคนละทาง เงินเดือนกรรมการบริษัทหักเป็นค่าใช้จ่ายได้ กำไรบริษัทลด ภาษีนิติบุคคลลด แต่ก้อนนั้นไปโผล่ในขั้นบันไดของคุณแทน ส่วนปันผลหักเป็นค่าใช้จ่ายไม่ได้ แปลว่ามันเสียภาษีนิติบุคคลมาแล้วรอบหนึ่ง แล้วเสีย 10% อีกตอนออกมา',
    en: 'Two routes, pulling against each other. A director’s salary is deductible, so the company’s profit and its tax both fall, but the same money lands on your own ladder instead. A dividend is not deductible: it has already paid corporate tax, and it pays 10% again on the way out.',
  },
  corpRevenue: { th: 'รายรับของบริษัท', en: 'Company revenue' },
  corpDrawOut: { th: 'เงินเดือนกรรมการ', en: 'Director’s salary' },
  corpTaxLabel: { th: 'ภาษีนิติบุคคล', en: 'Corporate tax' },
  corpRetained: { th: 'กำไรสะสมเข้าบริษัท', en: 'Kept by the company' },
  corpCash: { th: 'เงินสดในบริษัท', en: 'Company cash' },
  corpEquityLabel: { th: 'ส่วนของผู้ถือหุ้น (ของคุณ)', en: 'Shareholder equity (yours)' },
  corpCannotAfford: { th: 'บริษัทเงินไม่พอ', en: 'Company cannot afford it' },
  drawLabel: { th: 'เงินเดือนกรรมการ', en: 'Director’s salary' },
  drawTradeNote: {
    th: 'ถ้าขึ้นเงินเดือนตัวเองอีก 10,000 ครัวเรือนจะเหลือเงินต่างไป',
    en: 'Paying yourself ฿10,000 more a month would leave the household with',
  },
  dividendLabel: { th: 'จ่ายปันผลให้ตัวเอง', en: 'Pay yourself a dividend' },
  dividendNote: {
    th: 'ปันผลโดนหัก ณ ที่จ่าย 10% เงินก้อนนี้เสียภาษีนิติบุคคลมาแล้วรอบหนึ่ง นี่คือชั้นที่สอง',
    en: 'A dividend is withheld at 10%. This money already paid corporate tax; this is the second layer.',
  },
  fundLabel: { th: 'ใส่เงินเพิ่มทุนเข้าบริษัท', en: 'Put money into the company' },
  setIt: { th: 'ตั้งค่า', en: 'Set' },
  takeIt: { th: 'ถอนออก', en: 'Take it' },
  putIn: { th: 'ใส่เข้าไป', en: 'Put it in' },
  ownedByCorp: { th: 'ในนามบริษัท', en: 'company' },
  buyAsMe: { th: 'ซื้อในนามตัวเอง', en: 'Buy personally' },
  buyAsCorp: { th: 'ซื้อในนามบริษัท', en: 'Buy as the company' },
  buyAsCorpNote: {
    th: 'ซื้อในนามบริษัท รายได้จากตัวนี้จะเข้าบริษัทและเสียภาษีอัตรานิติบุคคล แต่จะเอามาใช้ส่วนตัวต้องถอนออกมาก่อน',
    en: 'Bought in the company’s name, its income belongs to the company and meets the company’s rate. Spending it personally means taking it out first.',
  },
  householdIncomeLabel: { th: 'เงินไหลเข้ารวมทั้งครัวเรือน', en: 'Household income' },
  passiveMine: { th: 'เงินไหลเข้าในชื่อคุณเอง', en: 'In your own name' },
  worthIfCashedOut: {
    th: 'ถ้าเลิกบริษัทแล้วถอนออกมาทั้งหมดวันนี้ เหลือจริง',
    en: 'If you wound the company up and took it all out today',
  },
  taxDisclaimer: {
    th: 'ตัวเลขในเกมยึดโครงของกฎหมายจริง แต่ตัดรายละเอียดออกเยอะเพื่อให้เล่นได้ ค่าลดหย่อนในชีวิตจริงมีอีกหลายสิบรายการ อย่าเอาไปใช้ยื่นภาษีจริงนะครับ',
    en: 'These figures follow the shape of the real law with most of the detail removed so it stays playable. Real life has dozens more allowances. Do not file with this.',
  },
  other: { th: 'ค่าใช้จ่ายอื่น ๆ', en: 'Other living costs' },
  childrenCost: { th: 'ค่าเลี้ยงลูก', en: 'Cost of children' },
  cashflow: { th: 'กระแสเงินสดต่อเดือน', en: 'Monthly cash flow' },
  cash: { th: 'เงินสด', en: 'Cash' },
  assets: { th: 'สินทรัพย์', en: 'Assets' },
  liabilities: { th: 'หนี้สิน', en: 'Liabilities' },
  netWorth: { th: 'ความมั่งคั่งสุทธิ', en: 'Net worth' },
  noAssets: { th: 'ยังไม่มีสินทรัพย์สักชิ้น', en: 'No assets yet' },
  noDebts: { th: 'ไม่มีหนี้เหลือแล้ว', en: 'No debts left' },
  payoff: { th: 'ปิดหนี้', en: 'Pay off' },
  holdings: { th: 'รายการ', en: 'holdings' },
  showMore: { th: 'ดูทั้งหมด', en: 'Show all' },
  showLess: { th: 'ย่อรายการ', en: 'Show less' },
  units: { th: 'หน่วย', en: 'units' },
  perMonth: { th: '/เดือน', en: '/mo' },

  /* board + controls */
  roll1: { th: 'ทอย 1 ลูก', en: 'Roll 1 die' },
  roll2: { th: 'ทอย 2 ลูก', en: 'Roll 2 dice' },
  turn: { th: 'ตาที่', en: 'Turn' },
  walking: { th: 'กำลังเดิน อีก', en: 'Moving, steps left:' },
  rolling: { th: 'กำลังทอย...', en: 'Rolling…' },
  months: { th: 'เดือนที่ผ่านไป', en: 'Months elapsed' },
  progress: { th: 'ความคืบหน้าสู่การหนีออก', en: 'Progress toward escape' },
  fastProgressLabel: { th: 'ความคืบหน้าสู่ชัยชนะ', en: 'Progress toward the win' },
  skipping: { th: 'ตกงาน ข้ามตา', en: 'Out of work' },
  charityLeft: { th: 'สิทธิ์ทอยสองลูก', en: 'Two-dice turns left' },
  log: { th: 'บันทึกเหตุการณ์', en: 'Event log' },
  borrowBtn: { th: 'เลือกยอดกู้เอง', en: 'Choose an amount' },

  /* tiles */
  tilePayday: { th: 'เงินเดือน', en: 'Payday' },
  tileDeal: { th: 'โอกาส', en: 'Deal' },
  tileMarket: { th: 'ตลาด', en: 'Market' },
  tileDoodad: { th: 'จิปาถะ', en: 'Doodad' },
  tileBaby: { th: 'มีลูก', en: 'Baby' },
  tileDownsized: { th: 'ตกงาน', en: 'Downsized' },
  tileCharity: { th: 'ทำบุญ', en: 'Charity' },
  tileFastpay: { th: 'รายได้เข้า', en: 'Income' },
  tileFastdeal: { th: 'ดีลทางด่วน', en: 'Fast deal' },
  tileFastmarket: { th: 'ตลาด', en: 'Market' },
  tileDream: { th: 'ความฝัน', en: 'Dream' },
  tileBonus: { th: 'โชคดี', en: 'Windfall' },
  tileSetback: { th: 'สะดุด', en: 'Setback' },

  /* card modals */
  chooseDeal: { th: 'เลือกขนาดดีล', en: 'Choose a deal size' },
  chooseDealHint: {
    th: 'ดีลเล็กใช้เงินน้อย เข้าถึงง่าย ดีลใหญ่ใช้เงินเยอะแต่เปลี่ยนเกมได้ในใบเดียว',
    en: 'Small deals are cheap and reachable. Big deals cost a lot and can change the game in one card.',
  },
  smallDeal: { th: 'ดีลเล็ก', en: 'Small deal' },
  bigDeal: { th: 'ดีลใหญ่', en: 'Big deal' },
  price: { th: 'ราคา', en: 'Price' },
  downPayment: { th: 'ใช้เงินสด', en: 'Cash needed' },
  loanTaken: { th: 'กู้เพิ่ม', en: 'Debt taken on' },
  monthlyIn: { th: 'เงินเข้าต่อเดือน', en: 'Monthly income' },
  totalCost: { th: 'รวมต้องจ่าย', en: 'Total to pay' },
  cappedAt: { th: 'ซื้อได้สูงสุด', en: 'capped at' },
  cardsWord: { th: 'ใบ', en: 'cards' },
  deckOneWay: {
    th: 'เลือกกองไหนแล้วต้องเปิดการ์ดจากกองนั้น ย้อนกลับมาเลือกใหม่ไม่ได้ ไม่งั้นก็แอบดูทั้งสองกองแล้วค่อยเลือกอันที่ดีกว่า แต่จะไม่ซื้อการ์ดที่เปิดมาก็ได้',
    en: 'Once you pick a deck you open a card from that deck; there is no going back, or you could peek at both and take the better one. You are never forced to buy the card you drew.',
  },
  qty: { th: 'จำนวน', en: 'Quantity' },
  buy: { th: 'ซื้อ', en: 'Buy' },
  pass: { th: 'ไม่เอา', en: 'Pass' },
  cannotAfford: { th: 'เงินสดไม่พอ', en: 'Not enough cash' },
  sell: { th: 'ขาย', en: 'Sell' },
  sellNone: { th: 'ไม่ขาย', en: 'Sell nothing' },
  marketNone: { th: 'ยังไม่ทำอะไร', en: 'Do nothing' },
  repairBill: { th: 'ค่าซ่อมทั้งหมด', en: 'The repair bill' },
  insurancePays: { th: 'ประกันรับไป', en: 'Insurance covers' },
  noCover: { th: 'ไม่มีประกันคุ้มครอง', en: 'No cover in force' },
  youPayItAll: { th: 'จ่ายเองเต็มจำนวน', en: 'All of it is yours' },
  youPay: { th: 'ค่าเสียหายส่วนแรกที่คุณจ่าย', en: 'Excess you pay' },
  coverInForce: { th: 'ตอนนี้ยังมีความคุ้มครองเหลืออยู่ ต่อเบี้ยตอนนี้คือต่ออายุไปอีกปี', en: 'Cover is still in force. Renewing now extends it another year.' },
  coverLapsed: { th: 'ตอนนี้ไม่มีความคุ้มครองเลย ถ้ารถมีเรื่องก่อนต่อเบี้ย ค่าซ่อมเป็นของคุณทั้งก้อน', en: 'There is no cover at all right now. Anything that happens before you renew is yours to pay in full.' },
  welcomeChild: { th: 'ยินดีต้อนรับ', en: 'Welcome them' },
  notNow: { th: 'ยังไม่พร้อม', en: 'Not now' },
  childrenTurn: { th: 'ลูกอายุครบ', en: 'They turn' },
  childrenAtSchool: { th: 'ลูกที่อยู่ในวัยเรียน', en: 'Children at school' },
  childCostNow: { th: 'ค่าเลี้ยงดูตอนนี้', en: 'Costs from today' },
  childCostLater: { th: 'ตอนเข้ามัธยม', en: 'By secondary school' },
  halfPrice: { th: 'ขายครึ่งราคาได้', en: 'Half price fetches' },
  minusItsDebt: { th: 'หักหนี้ที่ติดอยู่', en: 'less the debt on it' },
  andLoses: { th: 'และเสียเงินไหลเข้า', en: 'and gives up' },
  allUnderwater: {
    th: 'สินทรัพย์ทุกชิ้นที่คุณถืออยู่ ขายครึ่งราคาแล้วยังไม่พอปิดหนี้ที่ติดมากับมัน ขายไปนอกจากจะไม่ได้เงินสักบาท ธนาคารยังตามเก็บส่วนต่างที่เหลือต่ออีก นี่คือหน้าตาของการกู้มาซื้อจนเต็มเพดาน',
    en: 'Every asset you hold sells for less than the debt attached to it. Selling raises nothing at all and leaves the lender chasing you for the rest. This is what borrowing to the ceiling looks like from the inside.',
  },
  /** A sale that did not cover its own loan leaves a deficiency balance behind. */
  stillOwed: { th: 'ขายแล้วยังค้างหนี้', en: 'Still owed after the sale' },
  /** Fast-track cards pay once. The old label read as a permanent monthly income. */
  lumpSum: { th: 'รับเป็นเงินก้อนครั้งเดียว', en: 'One-off payment' },
  landTaken: { th: 'ที่ดินที่ถูกเวนคืน', en: 'The plot taken' },
  /** Car cover runs on a clock the player must be able to see. */
  coverChip: { th: 'ประกันรถเหลือ', en: 'Cover' },
  coverNone: { th: 'ไม่มีประกันรถ', en: 'No car cover' },
  deficiencyPay: { th: 'ผ่อนต่อ', en: 'repaid at' },
  age: { th: 'อายุ', en: 'Age' },
  yearsUnit: { th: 'ปี', en: '' },
  toRetire: { th: 'เกษียณอีก', en: 'to retire' },
  noRetire: { th: 'ไม่มีวันเกษียณ', en: 'No retirement date' },
  retiredTag: { th: 'เกษียณแล้ว', en: 'Retired' },
  careerEnded: { th: 'อาชีพจบแล้ว', en: 'Career over' },
  salaryEnded: { th: 'ไม่มีเงินเดือนแล้ว', en: 'No salary any more' },
  pensionNotYet: { th: 'ยังรับบำนาญไม่ได้ จนกว่าจะถึงอายุ', en: 'No pension until age' },
  pensionLabel: { th: 'บำนาญ', en: 'Pension' },
  pensionCivil: { th: 'บำนาญข้าราชการ', en: 'Civil service pension' },
  pensionSso: { th: 'บำนาญประกันสังคม', en: 'Social security pension' },
  pensionNone: { th: 'เบี้ยยังชีพผู้สูงอายุ', en: 'Old-age allowance' },
  retiredTitle: { th: 'ถึงวันที่เงินเดือนหยุด', en: 'The salary stops today' },
  retiredBody: {
    th: 'ตั้งแต่เดือนนี้ไม่มีเงินเดือนเข้าอีกแล้ว เหลือแค่บำนาญที่ระบบให้ กับเงินไหลเข้าที่คุณสร้างไว้เอง เกมยังไม่จบ แต่คำถามเปลี่ยนไปแล้ว จากสร้างทันไหม เป็นสิ่งที่สร้างไว้พอไหม',
    en: 'No salary from this month on. What is left is the pension the system gives you and the income you built yourself. The game is not over, but the question has changed from whether you would build in time to whether what you built is enough.',
  },
  inflationLabel: { th: 'ค่าครองชีพ', en: 'Cost of living' },
  sinceStart: { th: 'จากวันแรก', en: 'since day one' },
  studyLabel: { th: 'กำลังเรียน', en: 'Studying' },
  studyYearOf: { th: 'ปีที่', en: 'Year' },
  ofWord: { th: 'จาก', en: 'of' },
  termsLeft: { th: 'เหลืออีก', en: 'terms to go' },
  termsWord: { th: 'เทอม', en: '' },
  tuition: { th: 'ค่าเทอม', en: 'Tuition' },
  /** Tuition is charged as a lump when the term falls due, so the statement
   *  shows it as a bill on its way rather than a monthly line. */
  tuitionNextLabel: { th: 'ค่าเทอมงวดหน้า', en: 'Next term' },
  dueThisMonth: { th: 'เดือนนี้', en: 'this month' },
  dueInMonths: { th: 'อีก', en: 'in' },
  notInCashflow: { th: 'ยังไม่รวมในกระแสเงินสด จ่ายทีเดียวตอนถึงงวด', en: 'not in the cash-flow line: charged in full when the term falls due' },
  /** Graduation day: the job has already changed, and this is where it is said out loud. */
  gradTag: { th: 'เรียนจบ', en: 'Graduated' },
  gradTitle: { th: 'จบหลักสูตรแล้ว วันนี้คุณเปลี่ยนอาชีพ', en: 'The course is finished. Today the job changes.' },
  gradBody: {
    th: 'สิ่งที่เปลี่ยนไม่ได้มีแค่ชื่อตำแหน่ง เงินเดือนตั้งต้นต่ำกว่าคนที่อยู่มาก่อน และค่าใช้จ่ายประจำก็ขยับตามวิถีชีวิตของงานใหม่ด้วย ทั้งขาขึ้นและขาลง',
    en: 'More than the job title moves. The starting wage sits below what the people already there earn, and the running costs shift to match the life the new job comes with, in whichever direction that happens to be.',
  },
  gradFrom: { th: 'จากอาชีพ', en: 'From' },
  gradTo: { th: 'เป็น', en: 'To' },
  jobLabel: { th: 'อาชีพ', en: 'Job' },
  studyingTo: { th: 'เรียนเพื่อไปเป็น', en: 'studying to become' },
  /** After forty the baby tile becomes a reward instead of a first child. */
  rewardExamTag: { th: 'เรื่องดีของครอบครัว', en: 'Good news at home' },
  rewardExamTitle: { th: 'ลูกสอบได้ดีกว่าที่คิด', en: 'They did better than anyone expected' },
  rewardExamBody: {
    th: 'ผลสอบออกมาดีเกินคาด และลูกก็ยังไม่ได้ขออะไรเลยสักคำ คุณเป็นคนที่ตัดสินใจเองว่าจะฉลองยังไง และเดือนนี้กระเป๋าเงินก็มีสิทธิ์ออกเสียงด้วย',
    en: 'The results came back better than anyone hoped, and they have not asked for a thing. How this gets marked is entirely your call, and this month your wallet gets a vote too.',
  },
  rewardPetTag: { th: 'อีกหนึ่งสมาชิกในบ้าน', en: 'The other one at home' },
  rewardPetTitle: { th: 'ถึงรอบพา{petName}ไปหาหมอแล้ว', en: 'It is that time at the vet again for {petName}' },
  rewardPetBody: {
    th: '{pet} ไม่ได้เรียกคุณว่าพ่อแม่ แต่มันรอคุณอยู่ที่ประตูทุกวัน ค่าวัคซีน ค่าอาหาร ค่าของเล่นที่มันจะกัดพังภายในสามวัน รวมแล้วก็เท่ากับที่บ้านอื่นจ่ายให้ลูกอยู่ดี',
    en: '{pet} does not call you a parent, but waits by the door every day. Vaccinations, food, and a toy that will be destroyed within three days add up to roughly what other households spend on a child anyway.',
  },
  rewardPay: { th: 'จ่าย', en: 'Pay' },
  rewardSkip: { th: 'เดือนนี้ขอผ่านก่อน', en: 'Not this month' },
  careerTitle: { th: 'จะกลับไปทำงานเดิม หรือเปลี่ยนสาย', en: 'Back to the same work, or change lanes' },
  careerBody: {
    th: 'ตอนที่งานหลุดมือคือตอนที่คนส่วนใหญ่ตัดสินใจเรื่องนี้จริง ๆ เพราะมันเป็นตอนเดียวที่ไม่ต้องเสียอะไรเพิ่มเพื่อจะออก การเรียนไม่ได้ฟรี และราคาที่แพงที่สุดไม่ใช่ค่าเทอม',
    en: 'Losing the job is when most people actually face this, because it is the one moment leaving costs nothing extra. Studying is not free, and the tuition is not the expensive part.',
  },
  keepJob: { th: 'กลับไปทำงานเดิม', en: 'Go back to the same job' },
  enrolBtn: { th: 'สมัครเรียน', en: 'Enrol' },
  courseMonths: { th: 'ใช้เวลา', en: 'Takes' },
  monthsWord: { th: 'เดือน', en: 'months' },
  totalTuition: { th: 'ค่าเรียนทั้งหมด', en: 'Total tuition' },
  firstTerm: { th: 'จ่ายวันนี้เทอมแรก', en: 'Due today' },
  entryPayLabel: { th: 'เงินเดือนเริ่มต้น', en: 'Starting pay' },
  ofThatJob: { th: 'ของสายนั้น', en: 'of that job' },
  noSalaryWhile: { th: 'ไม่มีเงินเดือนตลอดหลักสูตร', en: 'No salary for the whole course' },
  keepWorking: { th: 'ทำงานประจำไปด้วยได้', en: 'Keep the day job' },
  pickTarget: { th: 'เรียนจบแล้วจะไปเป็น', en: 'Graduate into' },
  licenceTitle: { th: 'เรียนจบแล้ว เหลือค่าใบอนุญาต', en: 'Graduated. The licence is still unpaid' },
  licenceBody: {
    th: 'ใบอนุญาตประกอบวิชาชีพเป็นคนละก้อนกับค่าเรียน และไม่มีใบนี้ก็ทำงานไม่ได้ เลือกได้สามทาง แต่ละทางแพงคนละแบบ',
    en: 'The professional licence is a separate bill from the tuition, and without it the job does not exist. Three ways to pay, each expensive in its own way.',
  },
  payCash: { th: 'จ่ายด้วยเงินเก็บ', en: 'Pay from savings' },
  payLoan: { th: 'กู้มาจ่าย', en: 'Borrow it' },
  payBond: { th: 'รับทุน แล้วใช้ทุนคืน', en: 'Take the sponsorship' },
  bondNote: { th: 'ผูกสัญญา 36 เดือน หักเงินเดือน 25% ระหว่างนั้น', en: '36-month bond with 25% of the salary held back' },
  bondActive: { th: 'ติดสัญญาใช้ทุน', en: 'Bonded' },
  slumpActive: { th: 'รายได้หด', en: 'Takings down' },
  ifYouStop: { th: 'ถ้าอยู่ในวงล้อจนถึง 60', en: 'If you stay on the wheel until 60' },
  heirsLabel: { th: 'แบ่งให้ทายาท', en: 'Split between heirs' },
  perHeir: { th: 'ได้คนละ', en: 'each' },
  heirTax: { th: 'ภาษีที่ทายาทต้องจ่าย', en: 'Tax the heirs pay' },
  heirTaxNone: { th: 'ไม่ต้องเสียภาษีเลย', en: 'No tax at all' },
  splitNote: {
    th: 'ภาษีมรดกคิดกับผู้รับแต่ละคน ทายาทแต่ละคนจึงได้สิทธิยกเว้น 100 ล้านของตัวเอง แบ่งเท่า ๆ กันให้หลายคนจึงเสียภาษีน้อยกว่ายกให้คนเดียว',
    en: 'Thai inheritance tax is charged on each recipient, so every heir brings their own ฿100M exemption. Splitting equally between several costs less tax than leaving it all to one.',
  },
  carryCost: { th: 'ถือไว้เฉย ๆ ปีละ', en: 'Costs you a year to hold' },
  perYear: { th: '/ปี', en: ' a year' },
  totalDebt: { th: 'หนี้สินรวม', en: 'Total debt' },
  personalDebt: { th: 'หนี้ส่วนตัว', en: 'Personal debt' },
  assetDebt: { th: 'หนี้ที่ติดมากับสินทรัพย์', en: 'Debt riding on assets' },
  debtService: { th: 'ผ่อนรวมต่อเดือน', en: 'Debt service a month' },
  noDebt: { th: 'ไม่มีหนี้สินเลย', en: 'No debt at all' },
  buyAtThisPrice: { th: 'ซื้อที่ราคานี้', en: 'Buy at this price' },
  belowNormal: { th: 'ถูกกว่าราคาปกติ', en: 'below its usual price' },
  aboveNormal: { th: 'แพงกว่าราคาปกติ', en: 'above its usual price' },
  yearlyYield: { th: 'ผลตอบแทนต่อปี', en: 'Yield a year' },
  cheapYieldNote: {
    th: 'ราคาลง แต่เงินที่มันจ่ายให้ต่อหน่วยยังเท่าเดิม ถ้ามันจ่ายได้เท่าเดิมจริง ซื้อตอนนี้ก็เท่ากับได้ผลตอบแทนต่อเงินที่จ่ายสูงขึ้น',
    en: 'The price fell but the income per unit has not. If it keeps paying, the same money buys a bigger return today than it did last month.',
  },
  nothingToSell: { th: 'คุณไม่มีของที่ตรงกับข้อเสนอนี้', en: 'You hold nothing that matches this offer.' },
  offerPrice: { th: 'ราคาที่เขาให้', en: 'Their price' },
  pay: { th: 'จ่าย', en: 'Pay' },
  decline: { th: 'ปฏิเสธ', en: 'Decline' },
  instalmentBtn: { th: 'ขอผ่อนแทน', en: 'Take instalments' },
  ok: { th: 'รับทราบ', en: 'Continue' },
  babyBody: {
    th: 'จังหวะของการมีลูกมาถึงแล้ว ครอบครัวจะใหญ่ขึ้นหนึ่งคน ความสุขเพิ่มขึ้นเยอะ และรายจ่ายรายเดือนก็เพิ่มขึ้นตามไปด้วย แล้วยังเพิ่มอีกทุกครั้งที่ลูกโตขึ้นอีกขั้น เรื่องนี้เป็นการตัดสินใจ ไม่ใช่สิ่งที่เกมจะยัดใส่มือใคร',
    en: 'The moment has come round. The family would grow by one, joy would grow a lot, and the monthly bill would grow too, then grow again at every stage the child passes through. This is a decision, not something the game hands you.',
  },
  downsizedBody: {
    th: 'บริษัทลดขนาด สองเดือนถัดไปคุณไม่มีเงินเดือนเข้า แต่รายจ่ายยังเดินเท่าเดิมทุกเดือน สิ่งเดียวที่ช่วยได้คือเงินไหลเข้าที่คุณสร้างไว้แล้ว',
    en: 'The company downsized. For the next two months no salary arrives, while every expense carries on as usual. The only thing that softens it is the passive income you already built.',
  },
  downsizedCost: { th: 'สองเดือนนี้จะติดลบราว', en: 'Roughly the next two months' },
  downsizedSpare: { th: 'ผ่านสองเดือนแล้วจะเหลือราว', en: 'Left over after the two months' },
  quitPaused: {
    th: 'สองเดือนนี้จะยังลาออกไม่ได้ เพราะไม่มีงานให้ลาออก ปุ่มลาออกจะกลับมาตอนคุณกลับไปทำงาน',
    en: 'You cannot resign during these two months: there is no job left to resign from. The quit button returns on your first turn back at work.',
  },
  severance: { th: 'ค่าชดเชยที่ได้ทันที', en: 'Severance paid today' },
  keepLooking: { th: 'ปิดหน้าสรุป', en: 'Close summary' },
  seeSummary: { th: 'ดูสรุปอีกครั้ง', en: 'See summary' },
  wonBanner: { th: 'จบเกมแล้ว', en: 'Game over' },
  playedAs: { th: 'เล่นเป็น', en: 'Played as' },

  /* tiers, quitting, generosity */
  tier: { th: 'ระดับ', en: 'Tier' },
  nextTier: { th: 'ขั้นถัดไป', en: 'Next tier' },
  tierUpTitle: { th: 'เลื่อนขั้นแล้ว', en: 'Tier up' },
  keepPlaying: { th: 'เล่นต่อ', en: 'Keep playing' },
  quitTitle: { th: 'คุณลาออกได้แล้ว', en: 'You can quit now' },
  quitBody: {
    th: 'เงินไหลเข้าต่อเดือนของคุณมากกว่ารายจ่ายแล้ว แปลว่าเงินเดือนไม่จำเป็นอีกต่อไป ลาออกก็ได้ หรือจะอยู่ต่อเพื่อสะสมกันชนก่อนก็ได้ กดลาออกทีหลังจากปุ่มใต้กระดานได้ตลอด',
    en: 'Your passive income now covers every expense, so the salary is optional. Quit now, or stay on to build a buffer first; the button under the board is there whenever you want it.',
  },
  quitLose: { th: 'เงินเดือนที่จะหายไป', en: 'Salary you give up' },
  quitKeep: { th: 'เงินไหลเข้าที่เหลืออยู่', en: 'Passive income you keep' },
  quitBills: { th: 'รายจ่ายที่ยังต้องจ่าย', en: 'Expenses that carry on' },
  quitNow: { th: 'ลาออก', en: 'Quit the job' },
  stayOn: { th: 'ยังไม่ลาออก', en: 'Stay employed' },
  quitBtn: { th: 'ลาออกจากงาน', en: 'Quit your job' },
  endNow: { th: 'จบเกมและดูสรุป', en: 'End and see summary' },
  karma: { th: 'น้ำใจ', en: 'Generosity' },
  friendTitle: { th: 'เพื่อนยื่นมือมาช่วย', en: 'A friend steps in' },
  friendBody: {
    th: 'คนที่คุณเคยช่วยไว้รู้ว่าคุณกำลังลำบาก เลยโอนเงินมาให้ก้อนหนึ่ง ไม่คิดดอกเบี้ย ไม่มีกำหนดคืน ความสัมพันธ์เป็นสินทรัพย์ที่ไม่เคยโผล่ในงบดุล แต่มีค่าจริงตอนคับขัน',
    en: 'Someone you once helped hears you are struggling and sends money over: no interest, no deadline. Relationships never appear on a balance sheet, yet they pay out exactly when you need them to.',
  },
  friendAccept: { th: 'รับไว้ ขอบคุณเพื่อน', en: 'Accept, gratefully' },
  salaryGone: { th: 'ลาออกแล้ว ไม่มีเงินเดือน', en: 'Quit: no salary' },

  /* debt breakdown */
  debtDetail: { th: 'รายละเอียดหนี้', en: 'Debt detail' },
  interestPart: { th: 'ดอกเบี้ยเดือนนี้', en: 'Interest this month' },
  principalPart: { th: 'ตัดเงินต้น', en: 'Goes to principal' },
  monthsLeft: { th: 'เหลืออีกประมาณ', en: 'Roughly' },
  monthsUnitShort: { th: 'งวด', en: 'payments' },
  totalInterest: { th: 'ถ้าผ่อนจนจบ จ่ายดอกรวม', en: 'Total interest if paid to term' },
  bankNote: {
    th: 'ผ่อนเดือนละ 10% ของยอดที่กู้มา ก้อนนี้จึงหมดเร็ว แต่กินกระแสเงินสดหนักที่สุดในบรรดาหนี้ทั้งหมด',
    en: 'The payment is a tenth of what you drew, so it clears fast, and it eats more cash flow along the way than any other debt.',
  },
  payoffSaves: { th: 'ปิดตอนนี้ประหยัดดอกได้', en: 'Clearing it now saves' },
  sellNow: { th: 'ขายตอนนี้', en: 'Sell now' },
  livePrice: { th: 'ราคาตลาดตอนนี้', en: 'Price today' },
  resumeRun: { th: 'กลับไปเล่นต่อ', en: 'Keep playing' },
  clearMortgage: { th: 'ปิดหนี้ก้อนนี้', en: 'Clear this loan' },
  mortgageOn: { th: 'ค่าผ่อนต่อเดือน', en: 'Mortgage payment' },
  rentGross: { th: 'ค่าเช่าที่เก็บได้', en: 'Rent collected' },
  minusMortgage: { th: 'หักค่าผ่อนธนาคาร', en: 'Less the mortgage' },
  netToYou: { th: 'เข้ากระเป๋าคุณ', en: 'Left for you' },
  insideThePayment: { th: 'ในค่าผ่อนก้อนนั้น แบ่งเป็น', en: 'That payment splits into' },
  charityBody: {
    th: 'บริจาค 10% ของรายได้รวม แลกกับสิทธิ์เลือกทอย 1 หรือ 2 ลูกในสามตาถัดไป ทอยสองลูกทำให้คุณเดินได้ไกลขึ้น เจอโอกาสเร็วขึ้น',
    en: 'Donate 10% of total income for the right to roll one die or two for the next three turns. Two dice cover more ground and reach opportunities sooner.',
  },
  give: { th: 'บริจาค', en: 'Donate' },
  dontGive: { th: 'ไม่บริจาค', en: 'Skip' },

  /* rescue */
  rescueTitle: { th: 'เงินสดติดลบ', en: 'Cash has gone negative' },
  rescueBody: {
    th: 'ต้องหาเงินสดมาให้กลับเป็นบวกก่อนถึงจะเดินต่อได้ เลือกกู้ธนาคาร (ผ่อนคืนเดือนละ 10% ของยอดที่กู้ ราว 11 เดือนหมด) หรือขายสินทรัพย์ด่วนที่ครึ่งราคา',
    en: 'You must get back above zero before playing on: borrow from the bank (repaying 10% of the amount drawn each month, clearing in about eleven months) or fire-sell an asset at half price.',
  },
  fireSaleBtn: { th: 'ขายด่วนครึ่งราคา', en: 'Fire-sell at half price' },
  borrowTitle: { th: 'กู้เงินฉุกเฉิน', en: 'Emergency loan' },
  borrowBody: {
    th: 'ธนาคารดูว่าคุณผ่อนไหวแค่ไหน จึงให้กู้ได้ไม่เกินรายจ่าย 3 เดือนของคุณ กู้เป็นขั้นละ 10,000 ผ่อนคืนเดือนละ 10% ของยอดที่กู้ ประมาณ 11 เดือนก็หมด',
    en: 'The bank lends against what you can service, so the ceiling is three months of your expenses. Borrow in ฿10,000 steps and repay 10% of the amount drawn each month, clearing in about eleven months.',
  },
  borrowAmount: { th: 'ยอดที่จะกู้', en: 'Amount to borrow' },
  borrowCeiling: { th: 'กู้ได้อีกไม่เกิน', en: 'Still available' },
  borrowMonthly: { th: 'ผ่อนเดือนละ', en: 'Monthly payment' },
  borrowConfirm: { th: 'กู้เลย', en: 'Borrow' },
  borrowJustEnough: { th: 'กู้พอให้กลับเป็นบวก', en: 'Borrow just enough' },
  cancel: { th: 'ยกเลิก', en: 'Cancel' },

  /* animation speed */
  speed: { th: 'ความเร็ว', en: 'Speed' },
  speedNormal: { th: 'ปกติ', en: 'Normal' },
  speedFast: { th: 'เร็ว', en: 'Fast' },
  speedOff: { th: 'ข้าม', en: 'Skip' },

  /* fast track */
  fastTitle: { th: 'ทางด่วน', en: 'The fast track' },
  fastIntro: {
    th: 'คุณออกจากวงล้อแล้ว จากนี้ไม่มีเงินเดือน มีแต่เงินที่ไหลเข้าเอง ภาษีเปลี่ยนไปคิดจากเงินไหลเข้าแทนเงินเดือน ยิ่งพอร์ตโตขึ้นภาษีก็โตตาม ขั้นถัดไปคือสร้างรายได้เพิ่มให้ถึงเป้าด้านล่าง แล้วเก็บเงินไปซื้อความฝันของคุณ',
    en: 'You are off the wheel. No salary from here on, only income that arrives by itself, and the tax line now follows that income instead of a payslip, growing as the portfolio does. Next: build the extra monthly income shown below, then save up for your dream.',
  },
  fastGoalLabel: { th: 'เป้ารายได้เพิ่มต่อเดือน', en: 'Extra monthly income to reach' },
  fastIncome: { th: 'รายได้ทางด่วนต่อเดือน', en: 'Fast-track income' },
  yourDream: { th: 'ความฝันของคุณ', en: 'Your dream' },
  buyDream: { th: 'ซื้อความฝัน', en: 'Buy the dream' },
  dreamsDone: { th: 'ทำสำเร็จแล้ว', en: 'Achieved' },
  pickNextDream: { th: 'ตั้งความฝันข้อต่อไป', en: 'Set your next dream' },
  pickNextDreamBody: { th: 'ความฝันที่ทำไปแล้วไม่ต้องทำซ้ำ เลือกข้อถัดไปที่อยากไล่ตาม จะเลือกของถูกไว้ก่อนแล้วค่อยไต่ขึ้น หรือกระโดดไปข้อที่แพงที่สุดเลยก็ได้', en: 'A dream you have already achieved does not need doing twice. Pick the next one to chase: work up from the cheap end, or jump straight to the most expensive.' },
  swapDream: { th: 'เปลี่ยนความฝัน', en: 'Change dream' },
  dreamCollection: { th: 'ความฝันที่ทำสำเร็จ', en: 'Dreams achieved' },
  allDreamsDone: { th: 'ทำครบทุกข้อแล้ว', en: 'Every dream achieved' },
  notYet: { th: 'ยังไม่ซื้อ', en: 'Not yet' },
  invest: { th: 'ลงทุน', en: 'Invest' },

  /* fast-track deals + legacy */
  chooseFastHint: {
    th: 'ดีลทางด่วนคือของที่คุณซื้อได้เรื่อย ๆ ส่วนดีลระดับนายทุนคือกิจการที่ทั้งจังหวัดใช้บริการ ราคาหลักร้อยล้าน และมีคนได้ประโยชน์จากมันจริง ๆ',
    en: 'A fast-track deal is something you can keep buying. A capitalist deal is the sort of business a whole province uses: hundreds of millions, and real people on the other end of it.',
  },
  fastDealBtn: { th: 'ดีลทางด่วน', en: 'Fast-track deal' },
  megaDealBtn: { th: 'ดีลระดับนายทุน', en: 'Capitalist deal' },
  sellBiz: { th: 'ขายกิจการ', en: 'Sell the business' },
  closeBiz: { th: 'ปิดกิจการ', en: 'Close it down' },
  bizExitNote: { th: 'ขายเองได้ทันทีที่ 18 เท่าของกำไรต่อเดือน ถ้ารอคนซื้อบนช่องตลาดจะได้ 40 ถึง 60 เท่า', en: 'A private sale pays 18x monthly profit today. Waiting for a buyer on a market tile pays 40 to 60x.' },
  growing: { th: 'กำลังโต', en: 'growing' },
  shrinking: { th: 'กำลังแผ่ว', en: 'softening' },
  swingLabel: { th: 'รายได้แกว่งได้ถึง', en: 'Income can swing by' },
  leverageNote: {
    th: 'ดีลนี้กู้ธนาคารมาด้วย หนี้ก้อนนี้จึงติดไปกับตัวสินทรัพย์และโผล่ในงบ ตัวเลขเงินเข้าต่อเดือนหักค่าผ่อนให้แล้ว ยิ่งผ่อนไปเงินต้นยิ่งลด และถ้าปิดหนี้ได้ ค่าผ่อนทั้งก้อนจะกลายเป็นรายได้',
    en: 'This one is bought with a bank loan, so the debt travels with the asset and appears on your statement. The monthly income shown is already net of the payment, the principal falls every month, and clearing the loan turns the whole payment into income.',
  },
  impactLabel: { th: 'คนที่ได้ประโยชน์', en: 'People served' },

  legacyTitle: { th: 'มรดกที่ส่งต่อได้จริง', en: 'What actually gets passed on' },
  legacyBody: {
    th: 'ความฝันทำครบหมดแล้ว เงินยังโตต่อไปได้เรื่อย ๆ แต่คำถามเปลี่ยนไปแล้ว จากจะได้มาเท่าไหร่ เป็นของที่มีจะไปอยู่ที่ไหนต่อ',
    en: 'Every dream is achieved and the money can still grow, but the question has changed: from how much you get, to where any of it ends up.',
  },
  estateTaxDue: { th: 'ภาษีมรดกที่ทายาทจะโดน', en: 'Inheritance tax on your heirs' },
  estateTaxNone: { th: 'ยังไม่ถึงเกณฑ์ 100 ล้าน', en: 'Below the 100m threshold' },
  insuranceCover: { th: 'ทุนประกันชีวิต', en: 'Life cover' },
  donatedTotal: { th: 'บริจาคไปแล้ว', en: 'Given away' },
  optFoundation: { th: 'ตั้งมูลนิธิ', en: 'Endow a foundation' },
  optFoundationBody: {
    th: 'เงินก้อนนี้ออกจากงบของคุณถาวร ไม่มีรายได้กลับมา และไม่มีวันถูกคิดภาษีมรดก เพราะมันไม่ใช่ของคุณแล้ว',
    en: 'This money leaves your balance sheet for good. No income comes back, and it can never be taxed as your estate, because it is no longer yours.',
  },
  optCompany: { th: 'จดนิติบุคคล', en: 'Incorporate' },
  optCompanyBody: {
    th: 'ภาษีเปลี่ยนเป็นอัตราบริษัทแบบคงที่ แต่มีค่าบัญชีรายเดือนที่ต้องจ่ายไม่ว่าจะประหยัดได้หรือไม่ ดูตัวเลขประหยัดต่อเดือนก่อนตัดสินใจ',
    en: 'Tax moves to a flat company rate, against a monthly accounting bill you owe whether it saves anything or not. Check the monthly saving before deciding.',
  },
  optInsurance: { th: 'ทำประกันชีวิตทุนสูง', en: 'Take high life cover' },
  optInsuranceBody: {
    th: 'สินไหมมรณกรรมจ่ายตรงถึงผู้รับผลประโยชน์ จึงไม่ตกเป็นกองมรดกและไม่ถูกคิดภาษี แลกกับเบี้ยที่ต้องจ่ายทุกเดือนไปตลอด',
    en: 'The death benefit is paid straight to the beneficiary, so it never enters the estate and is never taxed. The premium is due every month for the rest of the game.',
  },
  setupCost: { th: 'ค่าจดทะเบียน', en: 'Setup cost' },
  savedPerMonth: { th: 'ประหยัดได้ต่อเดือน', en: 'Saved per month' },
  coverAdded: { th: 'ทุนประกันที่เพิ่ม', en: 'Cover added' },
  premium: { th: 'เบี้ยประกัน', en: 'Premium' },
  alreadyDone: { th: 'ทำแล้ว', en: 'done' },
  accounting: { th: 'ค่าบัญชีบริษัท', en: 'Company accounting' },
  legacyDisclaimer: {
    th: 'ตัวเลขในเกมย่อจากเกณฑ์จริง (ภาษีมรดกเก็บเฉพาะส่วนเกิน 100 ล้าน อัตรา 5% สำหรับลูกหลาน) เพื่อให้เล่นได้ ไม่ใช่คำแนะนำวางแผนภาษี ของจริงต้องคุยกับคนที่มีใบอนุญาต',
    en: 'These figures are simplified from the real thresholds (inheritance tax applies only above 100m, at 5% for direct descendants) so the game can be played. This is not tax advice; for the real thing, talk to someone licensed.',
  },

  /* endings */
  wonTitle: { th: 'คุณหนีออกมาได้แล้ว', en: 'You are out' },
  lostTitle: { th: 'ล้มละลาย', en: 'Bankrupt' },
  lostBody: {
    th: 'เงินสดติดลบจนไม่มีอะไรให้ขายและกู้ไม่ได้อีก ลองใหม่อีกรอบได้เลย รอบหน้าลองปิดหนี้ดอกสูงก่อนสะสมสินทรัพย์',
    en: 'Cash went negative with nothing left to sell and no credit left. Try again, and next time consider clearing the expensive debt before stacking assets.',
  },
  playAgain: { th: 'เล่นอีกรอบ', en: 'Play again' },
  summaryMonths: { th: 'ใช้เวลาไป', en: 'It took' },
  monthsUnit: { th: 'เดือน', en: 'months' },

  /* rules modal */
  rulesGoal: { th: 'เป้าหมาย', en: 'The goal' },
  rulesGoalBody: {
    th: 'คุณเริ่มในวงล้อ ที่ซึ่งรายได้เกือบทั้งหมดมาจากเงินเดือน และหยุดทำงานเมื่อไหร่รายได้ก็หยุดตาม เป้าหมายคือสะสมสินทรัพย์ที่ให้เงินไหลเข้าทุกเดือน จนเงินไหลเข้ามากกว่ารายจ่ายรวม แล้วคุณจะออกจากวงล้อไปสู่ทางด่วน',
    en: 'You start on the wheel, where nearly all income is salary and stops the moment you do. The goal is to stack assets that pay you monthly until that income covers every expense. Then you leave the wheel for the fast track.',
  },
  rulesTurn: { th: 'เล่นยังไง', en: 'How a turn works' },
  rulesTurnBody: {
    th: 'ทอยลูกเต๋าแล้วเดินตามช่อง แต่ละช่องมีเหตุการณ์ของมัน ช่องเงินเดือนจ่ายกระแสเงินสดหนึ่งเดือน (เดินผ่านก็ได้เงิน) ช่องโอกาสให้เลือกดีลเล็กหรือดีลใหญ่ ช่องตลาดคือคนมาขอซื้อของที่คุณถืออยู่ ช่องจิปาถะคือรายจ่ายจรที่โผล่มาตอนไม่ทันตั้งตัว',
    en: 'Roll, move, and resolve the tile you land on. Payday tiles pay one month of cash flow (passing one counts too). Deal tiles let you choose a small or big deal. Market tiles bring buyers for what you hold. Doodad tiles are the unplanned expenses that always arrive at the wrong moment.',
  },
  rulesMoney: { th: 'เรื่องเงินที่ควรรู้', en: 'The money rules' },
  rulesMoneyBody: {
    th: 'อสังหาฯ ใช้เงินดาวน์ไม่กี่เปอร์เซ็นต์ แต่หนี้ที่เหลือติดไปกับตัวสินทรัพย์ ตัวเลข "เงินเข้าต่อเดือน" บนการ์ดจึงหักค่าผ่อนให้แล้ว และทุกเดือนที่ผ่านไป ค่าผ่อนจะกินเงินต้นลงเรื่อย ๆ พอผ่อนหมด ค่าผ่อนก้อนนั้นจะกลายเป็นรายได้ของคุณเต็ม ๆ หุ้นไม่ให้เงินไหลเข้า (ยกเว้นตัวที่ระบุปันผล) กำไรมาจากขายตอนราคาขึ้นเท่านั้น ส่วนเงินกู้ฉุกเฉินกู้ได้ไม่เกินรายจ่าย 3 เดือน ผ่อนคืนเดือนละ 10% ของยอดที่กู้ ราว 11 เดือนก็หมด แต่ระหว่างนั้นกระแสเงินสดจะฝืดมาก',
    en: 'Property takes only a small down payment, and the remaining loan travels with the asset, so the “monthly income” printed on a card is already net of the mortgage. Every month that payment also chips away at the principal, and once the loan is gone the whole payment becomes yours. Shares pay nothing unless a dividend is stated; their profit comes only from selling higher. The emergency loan is capped at three months of expenses and repaid at 10% of the amount drawn each month, clearing in about eleven months, but cash is very tight until it does.',
  },
  rulesTiers: { th: 'ระดับนักลงทุน กับน้ำใจ', en: 'Investor tiers, and generosity' },
  rulesTiersBody: {
    th: 'ป้ายใต้ชื่อเกมคือระดับนักลงทุนของคุณ ไล่จากมนุษย์เงินเดือน ไปมือใหม่หัดลงทุน คนที่หนีออกมาได้ เจ้าของพอร์ต นักลงทุนอาชีพ และนายทุนเป็นขั้นสูงสุด ไม่มีอะไรจบเกมนอกจากล้มละลาย อยากเล่นต่อไปเรื่อย ๆ ก็ได้ อยากหยุดดูสรุปเมื่อไหร่ก็กดปุ่มจบเกมเอง ส่วน "น้ำใจ" ขึ้นเมื่อคุณรับการ์ดที่มีคนอื่นเกี่ยวข้อง เช่นให้ญาติยืมเงินหรือไปทริปกับเพื่อน และลดลงเมื่อปฏิเสธ ถ้าน้ำใจถึง 3 แล้วเงินสดติดลบ จะมีเพื่อนโอนเงินมาให้ก้อนหนึ่งโดยไม่คิดดอกเบี้ย ครั้งเดียวต่อเกม',
    en: 'The badge under the title is your investor tier: salary earner, first-time investor, off the wheel, debt-free owner, professional investor, and capitalist at the top. Nothing ends the game except bankruptcy, so play on as long as you like, or press the end button whenever you want the summary. Generosity rises when you accept a card that involves other people, such as lending to a relative or joining a trip, and falls when you decline. Reach 3 and go cash-negative, and a friend sends money over with no interest, once per game.',
  },
  rulesNote: { th: 'ที่มา', en: 'About this game' },
  rulesNoteBody: {
    th: 'เกมนี้เขียนขึ้นใหม่ทั้งหมดสำหรับเว็บนี้ ทั้งอาชีพ การ์ด ตัวเลข และถ้อยคำ ไม่ได้เกี่ยวข้องกับหรือได้รับอนุญาตจากเจ้าของเกมการเงินเชิงพาณิชย์รายใด กลไกพื้นฐานอย่างงบการเงินส่วนบุคคลและการวัดอิสรภาพจากเงินไหลเข้า เป็นแนวคิดสาธารณะที่ใครก็หยิบมาออกแบบเกมของตัวเองได้',
    en: 'Every profession, card, number and line of text here was written for this site. It is not affiliated with, or licensed by, any commercial financial board game. The underlying ideas, a personal income statement and measuring freedom by passive income, are public concepts anyone may build a game around.',
  },

  /* ------------------------------------------- setting a card aside a moment */
  setAside: { th: 'ย่อการ์ดไว้ก่อน ไปดูงบการเงิน', en: 'Set this aside and look at the statement' },
  backToCard: { th: 'กลับไปที่การ์ดที่ค้างอยู่', en: 'Back to the card waiting for you' },

  /* ------------------------------------------------- the bank's credit desk */
  creditTitle: { th: 'ฝ่ายสินเชื่อกำลังพิจารณา', en: 'The credit desk is reading your file' },
  creditBody: {
    th: 'ธนาคารไม่ได้ดูว่าคุณอยากได้เท่าไหร่ แต่ดูว่าคุณจ่ายคืนไหวแค่ไหน สี่บรรทัดข้างล่างคือสิ่งที่เขาเปิดดูจริง ๆ ก่อนเซ็นอนุมัติ',
    en: 'The bank is not looking at how much you want. It is looking at how much you can repay. The four lines below are what actually gets read before anyone signs.',
  },
  docIncome: { th: 'รายได้ที่ธนาคารนับให้', en: 'Income they will count' },
  docIncomeNote: {
    th: 'เงินเดือน บำนาญ และเงินเดือนกรรมการ นับเต็ม ส่วนค่าเช่ากับปันผล นับให้ 70% เพราะผู้เช่าย้ายออกได้และกิจการมีปีที่ไม่ดีได้',
    en: 'Salary, pension and a director’s wage count in full. Rent and dividends count at 70%, because tenants leave and businesses have bad years.',
  },
  dsrLabel: { th: 'ภาระผ่อนต่อรายได้ ถ้าอนุมัติ', en: 'Debt service if approved' },
  dsrCeiling: { th: 'เพดานที่ธนาคารรับได้', en: 'Their ceiling' },
  creditChance: { th: 'โอกาสผ่าน', en: 'Chance of approval' },
  chanceHigh: { th: 'สูง', en: 'high' },
  chanceMid: { th: 'ก้ำกึ่ง', en: 'borderline' },
  chanceLow: { th: 'ต่ำ', en: 'low' },
  factorIncome: { th: 'ฐานรายได้ประจำ', en: 'Documented income' },
  factorDsr: { th: 'สัดส่วนหนี้ต่อรายได้', en: 'Debt-to-income' },
  factorHistory: { th: 'ประวัติการชำระ', en: 'Repayment record' },
  factorBuffer: { th: 'เงินสดในมือตอนยื่น', en: 'Cash on the day' },
  verdictGood: { th: 'ผ่านสบาย', en: 'clean' },
  verdictFair: { th: 'พอไปได้', en: 'passable' },
  verdictPoor: { th: 'เป็นจุดอ่อน', en: 'a problem' },
  historyLine: { th: 'จ่ายตรงเวลา {on} เดือน · เดือนที่ปิดไม่ลง {late} · ปิดหนี้ครบ {done} ก้อน', en: '{on} months paid, {late} months short, {done} loans cleared' },
  applyLoan: { th: 'ยื่นขอสินเชื่อ', en: 'Apply' },
  loanBlocked: {
    th: 'ธนาคารเพิ่งปฏิเสธคำขอไป แฟ้มยังไม่ถูกเปิดใหม่จนถึงเดือนที่ {month}',
    en: 'The bank just declined you. They will not reopen the file until month {month}.',
  },
  loanRefused: { th: 'ไม่อนุมัติ', en: 'Declined' },
  loanPartial: { th: 'อนุมัติบางส่วน', en: 'Partly approved' },
  offerCut: { th: 'ขอเท่านี้ได้ แต่วงเงินที่เขาให้จริงคือ', en: 'You may ask for this, but the line they will actually grant is' },

  /* --------------------------------------------- renting and getting around */
  rentLabel: { th: 'ค่าเช่าบ้าน', en: 'Rent' },
  commuteLabel: { th: 'ค่าเดินทาง (ไม่มีรถ)', en: 'Getting around (no car)' },
  setupStep3: { th: '3. ตั้งต้นชีวิต', en: '3. How you start out' },
  setupStep3Hint: {
    th: 'เกมนี้เคยยัดรถกับบ้านพร้อมหนี้ใส่มือคุณตั้งแต่ตาแรก ทั้งที่มันคือการตัดสินใจที่คนส่วนใหญ่ได้เลือกจริง ๆ เลือกเอาว่าจะรับหนี้ก้อนนั้นไว้ หรือจะจ่ายอีกแบบหนึ่งแทน',
    en: 'The game used to hand you a car and a house with the loans already signed, when that is the one decision most people really do get to make. Take the debt, or pay for it the other way.',
  },
  takeCar: { th: 'ผ่อนรถต่อ', en: 'Keep the car' },
  skipCar: { th: 'ไม่มีรถ', en: 'No car' },
  takeHome: { th: 'ผ่อนบ้านต่อ', en: 'Keep the house' },
  skipHome: { th: 'เช่าอยู่', en: 'Rent instead' },
  carKeepNote: { th: 'ค่างวด {pay}/เดือน หนี้ {debt} ผ่อนหมดแล้วรถเป็นของคุณ', en: '{pay} a month against {debt} of debt. When it ends, the car is yours.' },
  carSkipNote: { th: 'ไม่มีหนี้ ไม่มีค่าซ่อม ไม่ต้องต่อประกัน แต่ค่าเดินทาง {cost}/เดือน และมันไม่มีวันหมด', en: 'No debt, no repairs, no policy to renew, but {cost} a month to get around and it never ends.' },
  homeKeepNote: { th: 'ค่างวด {pay}/เดือน หนี้ {debt} ทุกงวดกัดเงินต้นลงเรื่อย ๆ', en: '{pay} a month against {debt} of debt, and every payment eats into the principal.' },
  homeSkipNote: { th: 'ไม่มีหนี้บ้านเลย แต่ค่าเช่า {cost}/เดือน จ่ายไปสามสิบปีก็ยังไม่ได้เป็นเจ้าของอะไร', en: 'No mortgage at all, but {cost} a month of rent, and thirty years of it still owns you nothing.' },

  /* ------------------------------------------------------------- the animal */
  petAtHome: { th: 'สัตว์เลี้ยงที่บ้าน', en: 'At home' },
  partnerLabel: { th: 'ค่าใช้จ่ายกับคู่ชีวิต', en: 'Life with somebody else' },
  childCostHousehold: { th: 'ค่าเลี้ยงดูทั้งบ้าน', en: 'What the household pays' },
  childHalfNote: { th: 'ครึ่งหนึ่งของทั้งบ้าน', en: 'half of the household’s' },
  childShareNote: {
    th: 'ค่าเลี้ยงลูกหนึ่งคนของครอบครัวไทยทั่วไปอยู่ราวห้าพันถึงหนึ่งหมื่นบาทต่อเดือน งบนี้แสดงครึ่งเดียว เพราะอีกครึ่งเป็นของคู่ชีวิต ส่วนค่าเทอม วันเกิด และค่าหมอ คิดแยกเป็นการ์ดของมันเอง',
    en: 'An ordinary Thai family spends five to ten thousand baht a month on one child. This statement shows half of it, because the other adult pays the other half. School fees, birthdays and hospital nights are charged separately by their own cards.',
  },
  childCoverLabel: { th: 'เบี้ยประกันสุขภาพลูก', en: 'Children’s health cover' },
  homeOwned: { th: 'บ้านที่อยู่', en: 'The house you live in' },
  ownNote: { th: 'ราคาขยับขึ้นช้า ๆ ตามราคาที่ดินแถวนั้น', en: 'Drifting up slowly with land prices around it' },
  carOwned: { th: 'รถที่ขับอยู่', en: 'The car you drive' },
  thenRent: { th: 'จากนั้นต้องเช่าอยู่ เดือนละ', en: 'Then renting, at' },
  thenCommute: { th: 'จากนั้นต้องเดินทางเอง เดือนละ', en: 'Then getting around, at' },
  carNote: { th: 'มูลค่าลดลงทุกปี ปีแรก ๆ มักต่ำกว่ายอดหนี้ที่ยังเหลือ', en: 'Worth less every year, and for the first few years worth less than the loan on it' },

  /* --------------------------------------------------- reading a share card */
  booksTitle: { th: 'งบการเงินย่อ (ต่อปี)', en: 'The books (yearly)' },
  bookRevenue: { th: 'รายได้', en: 'Revenue' },
  bookProfit: { th: 'กำไรสุทธิ', en: 'Net profit' },
  bookGrowth: { th: 'รายได้โตจากปีก่อน', en: 'Revenue growth' },
  bookGearing: { th: 'หนี้ต่อทุน', en: 'Debt to equity' },
  bookPe: { th: 'ราคาต่อกำไร (P/E)', en: 'Price to earnings' },
  bookNoPe: { th: 'ยังไม่มีกำไรให้หาร', en: 'no earnings to divide by' },
  bookMillion: { th: 'ล้านบาท', en: '฿m' },
  goldNoBooks: {
    th: 'ทองไม่มีงบการเงินให้อ่าน เพราะทองไม่ได้ทำมาหากินอะไร มันไม่มีรายได้ ไม่มีกำไร ไม่จ่ายปันผล ราคาขึ้นลงตามคนอื่นอยากได้มันแค่ไหน',
    en: 'Gold has no books to read, because gold does not do any work. No revenue, no profit, no dividend. Its price is only ever what the next person will pay.',
  },

  /* ------------------------------------------- profit and loss on a holding */
  costBasis: { th: 'ต้นทุน', en: 'Cost' },
  unrealised: { th: 'กำไร/ขาดทุนบนกระดาษ', en: 'On paper' },

  /* ----------------------------------------------------- glossary popovers */
  whatIsIt: { th: 'คำนี้แปลว่าอะไร', en: 'What this means' },
  gloNetWorth: { th: 'ความมั่งคั่งสุทธิ', en: 'Net worth' },
  gloNetWorthBody: {
    th: 'ของทั้งหมดที่คุณมี ลบหนี้ทั้งหมดที่คุณติด เหลือเท่าไหร่คือความมั่งคั่งสุทธิ มันตอบคำถามว่า "ถ้าวันนี้ขายทุกอย่างแล้วใช้หนี้ให้หมด จะเหลือเงินเท่าไหร่" คนเงินเดือนเยอะแต่ติดหนี้เยอะ ตัวเลขนี้ติดลบได้สบาย ๆ',
    en: 'Everything you own minus everything you owe. It answers one question: if you sold it all today and paid off every debt, what would be left? A big salary with big debts sits below zero here without any trouble.',
  },
  gloCashflow: { th: 'กระแสเงินสด', en: 'Cash flow' },
  gloCashflowBody: {
    th: 'เงินเข้าทั้งเดือน ลบเงินออกทั้งเดือน เหลือติดลบแปลว่าเดือนนี้คุณจนลง ต่อให้มีทรัพย์สินเยอะแค่ไหนก็ตาม ความมั่งคั่งสุทธิบอกว่าคุณ "มี" เท่าไหร่ กระแสเงินสดบอกว่าคุณ "รอด" ในแต่ละเดือนไหม',
    en: 'Everything that came in this month minus everything that went out. Negative means this month made you poorer, however much you own. Net worth says what you have; cash flow says whether you get through the month.',
  },
  gloPassive: { th: 'เงินไหลเข้า (passive income)', en: 'Passive income' },
  gloPassiveBody: {
    th: 'เงินที่เข้ามาโดยคุณไม่ต้องไปนั่งทำงานแลก เช่นค่าเช่า ปันผล กำไรจากกิจการที่มีคนอื่นดูแล เกมนี้ชนะเมื่อตัวเลขนี้แซงรายจ่ายรวม ไม่ใช่เมื่อเงินเดือนขึ้น',
    en: 'Money that arrives without you sitting down to earn it: rent, dividends, the profit of a business somebody else runs. You win this game when this figure passes your total expenses, not when your salary rises.',
  },
  gloAssets: { th: 'ทรัพย์สิน', en: 'Assets' },
  gloAssetsBody: {
    th: 'ของที่ใส่เงินเข้ากระเป๋าคุณ หรืออย่างน้อยก็มีมูลค่าขายต่อได้ คำนี้ในเกมนับตามราคาตลาดวันนี้ ไม่ใช่ราคาที่คุณซื้อมา ของบางอย่างที่คนเรียกว่าทรัพย์สินในชีวิตจริง เช่นรถ กินเงินคุณทุกเดือนโดยไม่คืนอะไรเลย',
    en: 'Things that put money in your pocket, or at least things you could sell. Here they are counted at today’s market price, not what you paid. Some things people call assets, a car for instance, only ever take money out.',
  },
  gloLiabilities: { th: 'หนี้สิน', en: 'Liabilities' },
  gloLiabilitiesBody: {
    th: 'ยอดเงินต้นที่ยังค้างอยู่ทั้งหมด ทั้งหนี้ส่วนตัวและหนี้ที่ติดมากับทรัพย์สิน เช่นบ้านที่ยังผ่อนไม่หมด ตัวเลขนี้ไม่ใช่ค่างวดต่อเดือน แต่คือก้อนที่ต้องจ่ายจนครบ',
    en: 'The principal still outstanding, both your own debts and the ones riding on an asset such as a half-paid house. This is not the monthly payment; it is the lump that has to be cleared.',
  },
  gloDebtService: { th: 'ภาระผ่อนต่อเดือน', en: 'Debt service' },
  gloDebtServiceBody: {
    th: 'รวมค่างวดทุกก้อนที่ต้องจ่ายในหนึ่งเดือน ธนาคารสนใจตัวเลขนี้เทียบกับรายได้มากกว่าสนใจว่าคุณติดหนี้รวมเท่าไหร่ เพราะมันคือสิ่งที่ตัดสินว่าเดือนหน้าคุณยังจ่ายไหวไหม',
    en: 'Every instalment you owe in one month added up. A bank cares about this against your income far more than about the total you owe, because this is what decides whether next month goes badly.',
  },
  gloEquity: { th: 'ส่วนของเจ้าของ', en: 'Equity' },
  gloEquityBody: {
    th: 'ทรัพย์สินของบริษัท ลบหนี้ของบริษัท เหลือเท่าไหร่คือส่วนที่เป็นของคุณในฐานะเจ้าของหุ้น มันรวมอยู่ในความมั่งคั่งสุทธิแล้ว แต่จะเอาออกมาใช้จริงต้องจ่ายภาษีปันผลก่อน',
    en: 'What the company owns minus what it owes: the part that is yours as the shareholder. It is already inside your net worth, but getting it out to spend costs dividend tax first.',
  },
  gloDown: { th: 'เงินดาวน์', en: 'Down payment' },
  gloDownBody: {
    th: 'เงินสดที่ต้องวางเองตอนซื้อ ส่วนที่เหลือธนาคารออกให้ก่อนแล้วคุณผ่อนคืน ดาวน์น้อยแปลว่าใช้เงินคนอื่นเยอะ ซึ่งทั้งขยายกำไรและขยายความเจ็บพอ ๆ กัน',
    en: 'The cash you put down yourself; the bank fronts the rest and you repay it. A small deposit means using more of somebody else’s money, which magnifies the gain and the pain equally.',
  },

  /* ---------------------------------------------------- offers you can't take */
  butNoHolding: {
    th: 'แต่ตอนนี้คุณยังไม่มีของที่เขาอยากได้อยู่ในมือ ข้อเสนอนี้เลยผ่านไปเฉย ๆ',
    en: 'But you are holding nothing they want, so the offer simply passes you by.',
  },

  /* -------------------------------------------------------- the how-to screen */
  learnTitle: { th: 'อ่านก่อนเล่น 1 นาที', en: 'One minute before you start' },
  learnLead: {
    th: 'เกมนี้ไม่ได้วัดว่าใครเงินเดือนเยอะกว่า มันวัดว่าเงินที่ไหลเข้าโดยคุณไม่ต้องทำงาน โตทันรายจ่ายของคุณเมื่อไหร่',
    en: 'This game does not measure who earns more. It measures the month your income stops depending on you showing up.',
  },
  learn1: { th: 'เป้าหมายเดียว', en: 'The only goal' },
  learn1Body: {
    th: 'ชนะเมื่อ เงินไหลเข้าต่อเดือน มากกว่า รายจ่ายต่อเดือน ไม่เกี่ยวกับว่าคุณมีเงินสดเท่าไหร่ เพราะเงินก้อนหมดได้ แต่เงินไหลเข้ามันมาเองทุกเดือน',
    en: 'You win the month your passive income passes your expenses. Cash in hand is not the test: a lump runs out, and income that arrives every month does not.',
  },
  learn2: { th: 'หนึ่งตา เกิดอะไรบ้าง', en: 'What one turn does' },
  learn2Body: {
    th: 'ทอยลูกเต๋า เดินไปตามช่อง แล้วทำตามช่องที่หยุด ช่องเงินเดือนคือสิ้นเดือน เงินเข้าลบรายจ่ายทีเดียว ช่องโอกาสคือของให้ซื้อ ช่องตลาดคือคนมาขอซื้อของจากคุณ ช่องจ่ายคือบิลที่ไม่ได้เชิญมา',
    en: 'Roll, walk, and do what the tile says. Payday is the end of a month: income in, expenses out, all at once. Deals are things to buy, the market is somebody wanting to buy from you, and the expense tiles are bills nobody invited.',
  },
  learn3: { th: 'ซื้ออะไรถึงจะขยับ', en: 'What actually moves you' },
  learn3Body: {
    th: 'ของที่จ่ายเงินให้คุณทุกเดือน เช่นห้องปล่อยเช่า กองทุนอสังหาฯ หรือกิจการเล็ก ๆ จะดันเส้น "เงินไหลเข้า" ขึ้น ส่วนของที่หวังกำไรตอนขายอย่างหุ้นเก็งกำไรหรือทอง ไม่ขยับเส้นนั้นเลยจนกว่าคุณจะขายได้จริง',
    en: 'Things that pay you every month, a rented room, a property fund, a small business, push the passive-income line up. Things you hope to sell higher, a speculative share or gold, do nothing to that line until you actually sell.',
  },
  learn4: { th: 'หนี้ ไม่ได้แปลว่าแพ้', en: 'Debt is not the enemy' },
  learn4Body: {
    th: 'หนี้ที่เอาไปซื้อของที่จ่ายค่าเช่ากลับมามากกว่าค่างวด ทำให้คุณเร็วขึ้น หนี้ที่เอาไปซื้อของที่ไม่คืนอะไรเลย ทำให้เส้นชัยถอยห่างออกไปทุกเดือน เกมนี้แยกสองอย่างนี้ให้เห็นชัด ๆ',
    en: 'Debt that buys something paying more rent than the instalment makes you faster. Debt that buys something paying nothing pushes the finish line further away every month. The game keeps the two apart on purpose.',
  },
  learn5: { th: 'แพ้ยังไง', en: 'How you lose' },
  learn5Body: {
    th: 'เงินสดติดลบ ขายของก็ไม่พอ กู้ก็ไม่ผ่าน คือจบเกม ธนาคารในเกมนี้ดูรายได้ ดูสัดส่วนหนี้ และดูประวัติการจ่ายของคุณจริง ๆ ไม่ได้ปล่อยกู้ให้ทุกครั้งที่ขอ',
    en: 'Cash goes below zero, selling does not cover it, and the loan is declined. The bank here reads your income, your debt ratio and your payment record, and it does not say yes every time.',
  },
  learnGo: { th: 'เข้าใจแล้ว ไปเลือกอาชีพ', en: 'Got it, pick a job' },
  learnSkip: { th: 'ข้ามไปก่อน', en: 'Skip' },
  learnAgain: { th: 'วิธีเล่น', en: 'How to play' },
  learnDiagram: {
    th: 'แผนภาพ: เงินเดือนเข้ามาแล้วถูกรายจ่ายกินจนเกือบหมด ส่วนที่เหลือถ้าเอาไปซื้อทรัพย์สินที่จ่ายเงินคืน จะกลายเป็นเงินไหลเข้าที่โตขึ้นทุกเดือน จนวันหนึ่งสูงกว่ารายจ่าย นั่นคือวันที่คุณออกจากวงล้อได้',
    en: 'Diagram: a salary comes in and expenses eat nearly all of it. Whatever is left, spent on things that pay you back, becomes an income line that grows every month until it stands taller than the expenses. That is the day you step off the wheel.',
  },
} satisfies Record<string, Loc>;

export type UIKey = keyof typeof UI;

/**
 * Cut-down tile names. A 7-column ring gives each tile about 40px on a phone,
 * so nothing here goes past five characters; the full name of the tile the
 * player is standing on is spelled out in the middle of the board, and every
 * tile carries the long name in its aria-label.
 */
export const TILE_SHORT = {
  payday: { th: 'เงิน', en: 'Pay' },
  deal: { th: 'โอกาส', en: 'Deal' },
  market: { th: 'ตลาด', en: 'Mkt' },
  doodad: { th: 'จ่าย', en: 'Cost' },
  baby: { th: 'ลูก', en: 'Baby' },
  downsized: { th: 'ตกงาน', en: 'Fired' },
  charity: { th: 'บุญ', en: 'Give' },
  fastpay: { th: 'เงิน', en: 'Pay' },
  fastdeal: { th: 'ดีล', en: 'Deal' },
  fastmarket: { th: 'ตลาด', en: 'Mkt' },
  dream: { th: 'ฝัน', en: 'Dream' },
  bonus: { th: 'โชค', en: 'Luck' },
  setback: { th: 'สะดุด', en: 'Hit' },
} satisfies Record<string, Loc>;
