/** Every fixed label in the "หนีหนู" interface, in both languages. */
import type { Loc } from './types';

export const UI = {
  back: { th: 'หมวดเกม', en: 'All games' },
  gameTitle: { th: 'หนีหนู', en: 'Off the Wheel' },
  gameSub: {
    th: 'เกมกระดานการเงินที่คุณชนะเมื่อเงินไหลเข้าต่อเดือน มากกว่ารายจ่ายต่อเดือน',
    en: 'A financial board game you win the month your passive income outgrows your expenses.',
  },
  rules: { th: 'กติกา', en: 'Rules' },
  restart: { th: 'เริ่มใหม่', en: 'New game' },
  close: { th: 'ปิด', en: 'Close' },

  /* setup */
  setupStep1: { th: '1. เลือกอาชีพ', en: '1. Pick a job' },
  setupStep2: { th: '2. เลือกความฝัน', en: '2. Pick a dream' },
  setupHint: {
    th: 'อาชีพกำหนดเงินเดือน รายจ่าย และหนี้ตั้งต้น ยิ่งเงินเดือนสูง รายจ่ายยิ่งสูงตาม เส้นชัยจึงไม่ได้อยู่ที่ใครเงินเดือนเยอะกว่า',
    en: 'The job sets your salary, expenses and starting debts. Higher salaries come with higher expenses, so the finish line is not about who earns more.',
  },
  dreamHint: {
    th: 'ความฝันคือเป้าหมายสำรองบนทางด่วน ซื้อได้เมื่อไหร่ก็ชนะทันที ราคาต่างกันเกือบเจ็ดเท่า เลือกฝันใหญ่แปลว่าเลือกเกมที่ยาวขึ้น',
    en: 'The dream is your alternate goal on the fast track: buy it and you win on the spot. They differ almost sevenfold in price, so a bigger dream is a longer game.',
  },
  startGame: { th: 'เริ่มเล่น', en: 'Start' },
  resume: { th: 'เล่นต่อจากเกมเดิม', en: 'Resume saved game' },
  salary: { th: 'เงินเดือน', en: 'Salary' },
  startCash: { th: 'เงินสดตั้งต้น', en: 'Starting cash' },
  startCf: { th: 'กระแสเงินสด', en: 'Cash flow' },
  escapeNeed: { th: 'ต้องหาเงินไหลเข้าให้ถึง', en: 'Passive income needed' },
  /** on a job card the escape bar and the expense line are the same number, so
      they share one row instead of being printed twice */
  expensesIsBar: { th: 'รายจ่าย = เส้นชัย', en: 'Expenses = the bar' },

  /* statement */
  statement: { th: 'งบการเงินของคุณ', en: 'Your financial statement' },
  income: { th: 'รายได้', en: 'Income' },
  passive: { th: 'เงินไหลเข้า (passive)', en: 'Passive income' },
  expenses: { th: 'รายจ่าย', en: 'Expenses' },
  taxes: { th: 'ภาษี', en: 'Taxes' },
  other: { th: 'ค่าใช้จ่ายอื่น ๆ', en: 'Other living costs' },
  childrenCost: { th: 'ค่าเลี้ยงลูก', en: 'Cost of children' },
  cashflow: { th: 'กระแสเงินสดต่อเดือน', en: 'Monthly cash flow' },
  cash: { th: 'เงินสด', en: 'Cash' },
  assets: { th: 'สินทรัพย์', en: 'Assets' },
  liabilities: { th: 'หนี้สิน', en: 'Liabilities' },
  netWorth: { th: 'ความมั่งคั่งสุทธิ', en: 'Net worth' },
  noAssets: { th: 'ยังไม่มีสินทรัพย์สักชิ้น', en: 'No assets yet' },
  noDebts: { th: 'ไม่มีหนี้เหลือแล้ว', en: 'No debts left' },
  payoff: { th: 'ปิดหนี้', en: 'Pay off' },
  holdings: { th: 'รายการ', en: 'holdings' },
  showMore: { th: 'ดูทั้งหมด', en: 'Show all' },
  showLess: { th: 'ย่อรายการ', en: 'Show less' },
  units: { th: 'หน่วย', en: 'units' },
  perMonth: { th: '/เดือน', en: '/mo' },

  /* board + controls */
  roll1: { th: 'ทอย 1 ลูก', en: 'Roll 1 die' },
  roll2: { th: 'ทอย 2 ลูก', en: 'Roll 2 dice' },
  turn: { th: 'ตาที่', en: 'Turn' },
  walking: { th: 'กำลังเดิน อีก', en: 'Moving, steps left:' },
  rolling: { th: 'กำลังทอย...', en: 'Rolling…' },
  months: { th: 'เดือนที่ผ่านไป', en: 'Months elapsed' },
  progress: { th: 'ความคืบหน้าสู่การหนีออก', en: 'Progress toward escape' },
  fastProgressLabel: { th: 'ความคืบหน้าสู่ชัยชนะ', en: 'Progress toward the win' },
  skipping: { th: 'ตกงาน ข้ามตา', en: 'Out of work' },
  charityLeft: { th: 'สิทธิ์ทอยสองลูก', en: 'Two-dice turns left' },
  log: { th: 'บันทึกเหตุการณ์', en: 'Event log' },
  borrowBtn: { th: 'เลือกยอดกู้เอง', en: 'Choose an amount' },

  /* tiles */
  tilePayday: { th: 'เงินเดือน', en: 'Payday' },
  tileDeal: { th: 'โอกาส', en: 'Deal' },
  tileMarket: { th: 'ตลาด', en: 'Market' },
  tileDoodad: { th: 'จิปาถะ', en: 'Doodad' },
  tileBaby: { th: 'มีลูก', en: 'Baby' },
  tileDownsized: { th: 'ตกงาน', en: 'Downsized' },
  tileCharity: { th: 'ทำบุญ', en: 'Charity' },
  tileFastpay: { th: 'รายได้เข้า', en: 'Income' },
  tileFastdeal: { th: 'ดีลทางด่วน', en: 'Fast deal' },
  tileFastmarket: { th: 'ตลาด', en: 'Market' },
  tileDream: { th: 'ความฝัน', en: 'Dream' },
  tileBonus: { th: 'โชคดี', en: 'Windfall' },
  tileSetback: { th: 'สะดุด', en: 'Setback' },

  /* card modals */
  chooseDeal: { th: 'เลือกขนาดดีล', en: 'Choose a deal size' },
  chooseDealHint: {
    th: 'ดีลเล็กใช้เงินน้อย เข้าถึงง่าย ดีลใหญ่ใช้เงินเยอะแต่เปลี่ยนเกมได้ในใบเดียว',
    en: 'Small deals are cheap and reachable. Big deals cost a lot and can change the game in one card.',
  },
  smallDeal: { th: 'ดีลเล็ก', en: 'Small deal' },
  bigDeal: { th: 'ดีลใหญ่', en: 'Big deal' },
  price: { th: 'ราคา', en: 'Price' },
  downPayment: { th: 'ใช้เงินสด', en: 'Cash needed' },
  loanTaken: { th: 'กู้เพิ่ม', en: 'Debt taken on' },
  monthlyIn: { th: 'เงินเข้าต่อเดือน', en: 'Monthly income' },
  totalCost: { th: 'รวมต้องจ่าย', en: 'Total to pay' },
  cappedAt: { th: 'ซื้อได้สูงสุด', en: 'capped at' },
  cardsWord: { th: 'ใบ', en: 'cards' },
  deckOneWay: {
    th: 'เลือกกองไหนแล้วต้องเปิดการ์ดจากกองนั้น ย้อนกลับมาเลือกใหม่ไม่ได้ ไม่งั้นก็แอบดูทั้งสองกองแล้วค่อยเลือกอันที่ดีกว่า แต่จะไม่ซื้อการ์ดที่เปิดมาก็ได้',
    en: 'Once you pick a deck you open a card from that deck; there is no going back, or you could peek at both and take the better one. You are never forced to buy the card you drew.',
  },
  qty: { th: 'จำนวน', en: 'Quantity' },
  buy: { th: 'ซื้อ', en: 'Buy' },
  pass: { th: 'ไม่เอา', en: 'Pass' },
  cannotAfford: { th: 'เงินสดไม่พอ', en: 'Not enough cash' },
  sell: { th: 'ขาย', en: 'Sell' },
  sellNone: { th: 'ไม่ขาย', en: 'Sell nothing' },
  marketNone: { th: 'ยังไม่ทำอะไร', en: 'Do nothing' },
  halfPrice: { th: 'ขายครึ่งราคาได้', en: 'Half price fetches' },
  minusItsDebt: { th: 'หักหนี้ที่ติดอยู่', en: 'less the debt on it' },
  andLoses: { th: 'และเสียเงินไหลเข้า', en: 'and gives up' },
  allUnderwater: {
    th: 'สินทรัพย์ทุกชิ้นที่คุณถืออยู่ ขายครึ่งราคาแล้วยังไม่พอปิดหนี้ที่ติดมากับมัน ขายไปก็ไม่ได้เงินสักบาท ได้แค่หยุดค่างวด นี่คือหน้าตาของการกู้มาซื้อจนเต็มเพดาน',
    en: 'Every asset you hold sells for less than the debt attached to it, so selling raises nothing at all and only stops the payments. This is what borrowing to the ceiling looks like from the inside.',
  },
  age: { th: 'อายุ', en: 'Age' },
  yearsUnit: { th: 'ปี', en: '' },
  toRetire: { th: 'เกษียณอีก', en: 'to retire' },
  noRetire: { th: 'ไม่มีวันเกษียณ', en: 'No retirement date' },
  retiredTag: { th: 'เกษียณแล้ว', en: 'Retired' },
  careerEnded: { th: 'อาชีพจบแล้ว', en: 'Career over' },
  salaryEnded: { th: 'ไม่มีเงินเดือนแล้ว', en: 'No salary any more' },
  pensionNotYet: { th: 'ยังรับบำนาญไม่ได้ จนกว่าจะถึงอายุ', en: 'No pension until age' },
  pensionLabel: { th: 'บำนาญ', en: 'Pension' },
  pensionCivil: { th: 'บำนาญข้าราชการ', en: 'Civil service pension' },
  pensionSso: { th: 'บำนาญประกันสังคม', en: 'Social security pension' },
  pensionNone: { th: 'เบี้ยยังชีพผู้สูงอายุ', en: 'Old-age allowance' },
  retiredTitle: { th: 'ถึงวันที่เงินเดือนหยุด', en: 'The salary stops today' },
  retiredBody: {
    th: 'ตั้งแต่เดือนนี้ไม่มีเงินเดือนเข้าอีกแล้ว เหลือแค่บำนาญที่ระบบให้ กับเงินไหลเข้าที่คุณสร้างไว้เอง เกมยังไม่จบ แต่คำถามเปลี่ยนไปแล้ว จากสร้างทันไหม เป็นสิ่งที่สร้างไว้พอไหม',
    en: 'No salary from this month on. What is left is the pension the system gives you and the income you built yourself. The game is not over, but the question has changed from whether you would build in time to whether what you built is enough.',
  },
  inflationLabel: { th: 'ค่าครองชีพ', en: 'Cost of living' },
  sinceStart: { th: 'จากวันแรก', en: 'since day one' },
  studyLabel: { th: 'กำลังเรียน', en: 'Studying' },
  studyYearOf: { th: 'ปีที่', en: 'Year' },
  ofWord: { th: 'จาก', en: 'of' },
  termsLeft: { th: 'เหลืออีก', en: 'terms to go' },
  termsWord: { th: 'เทอม', en: '' },
  tuition: { th: 'ค่าเทอม', en: 'Tuition' },
  careerTitle: { th: 'จะกลับไปทำงานเดิม หรือเปลี่ยนสาย', en: 'Back to the same work, or change lanes' },
  careerBody: {
    th: 'ตอนที่งานหลุดมือคือตอนที่คนส่วนใหญ่ตัดสินใจเรื่องนี้จริง ๆ เพราะมันเป็นตอนเดียวที่ไม่ต้องเสียอะไรเพิ่มเพื่อจะออก การเรียนไม่ได้ฟรี และราคาที่แพงที่สุดไม่ใช่ค่าเทอม',
    en: 'Losing the job is when most people actually face this, because it is the one moment leaving costs nothing extra. Studying is not free, and the tuition is not the expensive part.',
  },
  keepJob: { th: 'กลับไปทำงานเดิม', en: 'Go back to the same job' },
  enrolBtn: { th: 'สมัครเรียน', en: 'Enrol' },
  courseMonths: { th: 'ใช้เวลา', en: 'Takes' },
  monthsWord: { th: 'เดือน', en: 'months' },
  totalTuition: { th: 'ค่าเรียนทั้งหมด', en: 'Total tuition' },
  firstTerm: { th: 'จ่ายวันนี้เทอมแรก', en: 'Due today' },
  entryPayLabel: { th: 'เงินเดือนเริ่มต้น', en: 'Starting pay' },
  ofThatJob: { th: 'ของสายนั้น', en: 'of that job' },
  noSalaryWhile: { th: 'ไม่มีเงินเดือนตลอดหลักสูตร', en: 'No salary for the whole course' },
  keepWorking: { th: 'ทำงานประจำไปด้วยได้', en: 'Keep the day job' },
  pickTarget: { th: 'เรียนจบแล้วจะไปเป็น', en: 'Graduate into' },
  licenceTitle: { th: 'เรียนจบแล้ว เหลือค่าใบอนุญาต', en: 'Graduated. The licence is still unpaid' },
  licenceBody: {
    th: 'ใบอนุญาตประกอบวิชาชีพเป็นคนละก้อนกับค่าเรียน และไม่มีใบนี้ก็ทำงานไม่ได้ เลือกได้สามทาง แต่ละทางแพงคนละแบบ',
    en: 'The professional licence is a separate bill from the tuition, and without it the job does not exist. Three ways to pay, each expensive in its own way.',
  },
  payCash: { th: 'จ่ายด้วยเงินเก็บ', en: 'Pay from savings' },
  payLoan: { th: 'กู้มาจ่าย', en: 'Borrow it' },
  payBond: { th: 'รับทุน แล้วใช้ทุนคืน', en: 'Take the sponsorship' },
  bondNote: { th: 'ผูกสัญญา 36 เดือน หักเงินเดือน 25% ระหว่างนั้น', en: '36-month bond with 25% of the salary held back' },
  bondActive: { th: 'ติดสัญญาใช้ทุน', en: 'Bonded' },
  slumpActive: { th: 'รายได้หด', en: 'Takings down' },
  ifYouStop: { th: 'ถ้าอยู่ในวงล้อจนถึง 60', en: 'If you stay on the wheel until 60' },
  heirsLabel: { th: 'แบ่งให้ทายาท', en: 'Split between heirs' },
  perHeir: { th: 'ได้คนละ', en: 'each' },
  heirTax: { th: 'ภาษีที่ทายาทต้องจ่าย', en: 'Tax the heirs pay' },
  heirTaxNone: { th: 'ไม่ต้องเสียภาษีเลย', en: 'No tax at all' },
  splitNote: {
    th: 'ภาษีมรดกคิดกับผู้รับแต่ละคน ทายาทแต่ละคนจึงได้สิทธิยกเว้น 100 ล้านของตัวเอง แบ่งเท่า ๆ กันให้หลายคนจึงเสียภาษีน้อยกว่ายกให้คนเดียว',
    en: 'Thai inheritance tax is charged on each recipient, so every heir brings their own ฿100M exemption. Splitting equally between several costs less tax than leaving it all to one.',
  },
  carryCost: { th: 'ถือไว้เฉย ๆ ปีละ', en: 'Costs you a year to hold' },
  perYear: { th: '/ปี', en: ' a year' },
  totalDebt: { th: 'หนี้สินรวม', en: 'Total debt' },
  personalDebt: { th: 'หนี้ส่วนตัว', en: 'Personal debt' },
  assetDebt: { th: 'หนี้ที่ติดมากับสินทรัพย์', en: 'Debt riding on assets' },
  debtService: { th: 'ผ่อนรวมต่อเดือน', en: 'Debt service a month' },
  noDebt: { th: 'ไม่มีหนี้สินเลย', en: 'No debt at all' },
  buyAtThisPrice: { th: 'ซื้อที่ราคานี้', en: 'Buy at this price' },
  belowNormal: { th: 'ถูกกว่าราคาปกติ', en: 'below its usual price' },
  aboveNormal: { th: 'แพงกว่าราคาปกติ', en: 'above its usual price' },
  yearlyYield: { th: 'ผลตอบแทนต่อปี', en: 'Yield a year' },
  cheapYieldNote: {
    th: 'ราคาลง แต่เงินที่มันจ่ายให้ต่อหน่วยยังเท่าเดิม ถ้ามันจ่ายได้เท่าเดิมจริง ซื้อตอนนี้ก็เท่ากับได้ผลตอบแทนต่อเงินที่จ่ายสูงขึ้น',
    en: 'The price fell but the income per unit has not. If it keeps paying, the same money buys a bigger return today than it did last month.',
  },
  nothingToSell: { th: 'คุณไม่มีของที่ตรงกับข้อเสนอนี้', en: 'You hold nothing that matches this offer.' },
  offerPrice: { th: 'ราคาที่เขาให้', en: 'Their price' },
  pay: { th: 'จ่าย', en: 'Pay' },
  decline: { th: 'ปฏิเสธ', en: 'Decline' },
  instalmentBtn: { th: 'ขอผ่อนแทน', en: 'Take instalments' },
  ok: { th: 'รับทราบ', en: 'Continue' },
  babyBody: {
    th: 'ครอบครัวใหญ่ขึ้นหนึ่งคน ความสุขเพิ่มขึ้นเยอะ และรายจ่ายรายเดือนก็เพิ่มขึ้นตามไปด้วย',
    en: 'The family grows by one. So does joy, and so does the monthly expense line.',
  },
  downsizedBody: {
    th: 'บริษัทลดขนาด สองเดือนถัดไปคุณไม่มีเงินเดือนเข้า แต่รายจ่ายยังเดินเท่าเดิมทุกเดือน สิ่งเดียวที่ช่วยได้คือเงินไหลเข้าที่คุณสร้างไว้แล้ว',
    en: 'The company downsized. For the next two months no salary arrives, while every expense carries on as usual. The only thing that softens it is the passive income you already built.',
  },
  downsizedCost: { th: 'สองเดือนนี้จะติดลบราว', en: 'Roughly the next two months' },
  downsizedSpare: { th: 'ผ่านสองเดือนแล้วจะเหลือราว', en: 'Left over after the two months' },
  quitPaused: {
    th: 'สองเดือนนี้จะยังลาออกไม่ได้ เพราะไม่มีงานให้ลาออก ปุ่มลาออกจะกลับมาตอนคุณกลับไปทำงาน',
    en: 'You cannot resign during these two months: there is no job left to resign from. The quit button returns on your first turn back at work.',
  },
  severance: { th: 'ค่าชดเชยที่ได้ทันที', en: 'Severance paid today' },
  keepLooking: { th: 'ปิดหน้าสรุป', en: 'Close summary' },
  seeSummary: { th: 'ดูสรุปอีกครั้ง', en: 'See summary' },
  wonBanner: { th: 'จบเกมแล้ว', en: 'Game over' },
  playedAs: { th: 'เล่นเป็น', en: 'Played as' },

  /* tiers, quitting, generosity */
  tier: { th: 'ระดับ', en: 'Tier' },
  nextTier: { th: 'ขั้นถัดไป', en: 'Next tier' },
  tierUpTitle: { th: 'เลื่อนขั้นแล้ว', en: 'Tier up' },
  keepPlaying: { th: 'เล่นต่อ', en: 'Keep playing' },
  quitTitle: { th: 'คุณลาออกได้แล้ว', en: 'You can quit now' },
  quitBody: {
    th: 'เงินไหลเข้าต่อเดือนของคุณมากกว่ารายจ่ายแล้ว แปลว่าเงินเดือนไม่จำเป็นอีกต่อไป ลาออกก็ได้ หรือจะอยู่ต่อเพื่อสะสมกันชนก่อนก็ได้ กดลาออกทีหลังจากปุ่มใต้กระดานได้ตลอด',
    en: 'Your passive income now covers every expense, so the salary is optional. Quit now, or stay on to build a buffer first; the button under the board is there whenever you want it.',
  },
  quitLose: { th: 'เงินเดือนที่จะหายไป', en: 'Salary you give up' },
  quitKeep: { th: 'เงินไหลเข้าที่เหลืออยู่', en: 'Passive income you keep' },
  quitBills: { th: 'รายจ่ายที่ยังต้องจ่าย', en: 'Expenses that carry on' },
  quitNow: { th: 'ลาออก', en: 'Quit the job' },
  stayOn: { th: 'ยังไม่ลาออก', en: 'Stay employed' },
  quitBtn: { th: 'ลาออกจากงาน', en: 'Quit your job' },
  endNow: { th: 'จบเกมและดูสรุป', en: 'End and see summary' },
  karma: { th: 'น้ำใจ', en: 'Generosity' },
  friendTitle: { th: 'เพื่อนยื่นมือมาช่วย', en: 'A friend steps in' },
  friendBody: {
    th: 'คนที่คุณเคยช่วยไว้รู้ว่าคุณกำลังลำบาก เลยโอนเงินมาให้ก้อนหนึ่ง ไม่คิดดอกเบี้ย ไม่มีกำหนดคืน ความสัมพันธ์เป็นสินทรัพย์ที่ไม่เคยโผล่ในงบดุล แต่มีค่าจริงตอนคับขัน',
    en: 'Someone you once helped hears you are struggling and sends money over: no interest, no deadline. Relationships never appear on a balance sheet, yet they pay out exactly when you need them to.',
  },
  friendAccept: { th: 'รับไว้ ขอบคุณเพื่อน', en: 'Accept, gratefully' },
  salaryGone: { th: 'ลาออกแล้ว ไม่มีเงินเดือน', en: 'Quit: no salary' },

  /* debt breakdown */
  debtDetail: { th: 'รายละเอียดหนี้', en: 'Debt detail' },
  interestPart: { th: 'ดอกเบี้ยเดือนนี้', en: 'Interest this month' },
  principalPart: { th: 'ตัดเงินต้น', en: 'Goes to principal' },
  monthsLeft: { th: 'เหลืออีกประมาณ', en: 'Roughly' },
  monthsUnitShort: { th: 'งวด', en: 'payments' },
  totalInterest: { th: 'ถ้าผ่อนจนจบ จ่ายดอกรวม', en: 'Total interest if paid to term' },
  bankNote: {
    th: 'ผ่อนเดือนละ 10% ของยอดที่กู้มา ก้อนนี้จึงหมดเร็ว แต่กินกระแสเงินสดหนักที่สุดในบรรดาหนี้ทั้งหมด',
    en: 'The payment is a tenth of what you drew, so it clears fast, and it eats more cash flow along the way than any other debt.',
  },
  payoffSaves: { th: 'ปิดตอนนี้ประหยัดดอกได้', en: 'Clearing it now saves' },
  sellNow: { th: 'ขายตอนนี้', en: 'Sell now' },
  livePrice: { th: 'ราคาตลาดตอนนี้', en: 'Price today' },
  resumeRun: { th: 'กลับไปเล่นต่อ', en: 'Keep playing' },
  clearMortgage: { th: 'ปิดหนี้ก้อนนี้', en: 'Clear this loan' },
  mortgageOn: { th: 'ค่าผ่อนต่อเดือน', en: 'Mortgage payment' },
  rentGross: { th: 'ค่าเช่าที่เก็บได้', en: 'Rent collected' },
  minusMortgage: { th: 'หักค่าผ่อนธนาคาร', en: 'Less the mortgage' },
  netToYou: { th: 'เข้ากระเป๋าคุณ', en: 'Left for you' },
  insideThePayment: { th: 'ในค่าผ่อนก้อนนั้น แบ่งเป็น', en: 'That payment splits into' },
  charityBody: {
    th: 'บริจาค 10% ของรายได้รวม แลกกับสิทธิ์เลือกทอย 1 หรือ 2 ลูกในสามตาถัดไป ทอยสองลูกทำให้คุณเดินได้ไกลขึ้น เจอโอกาสเร็วขึ้น',
    en: 'Donate 10% of total income for the right to roll one die or two for the next three turns. Two dice cover more ground and reach opportunities sooner.',
  },
  give: { th: 'บริจาค', en: 'Donate' },
  dontGive: { th: 'ไม่บริจาค', en: 'Skip' },

  /* rescue */
  rescueTitle: { th: 'เงินสดติดลบ', en: 'Cash has gone negative' },
  rescueBody: {
    th: 'ต้องหาเงินสดมาให้กลับเป็นบวกก่อนถึงจะเดินต่อได้ เลือกกู้ธนาคาร (ผ่อนคืนเดือนละ 10% ของยอดที่กู้ ราว 11 เดือนหมด) หรือขายสินทรัพย์ด่วนที่ครึ่งราคา',
    en: 'You must get back above zero before playing on: borrow from the bank (repaying 10% of the amount drawn each month, clearing in about eleven months) or fire-sell an asset at half price.',
  },
  fireSaleBtn: { th: 'ขายด่วนครึ่งราคา', en: 'Fire-sell at half price' },
  borrowTitle: { th: 'กู้เงินฉุกเฉิน', en: 'Emergency loan' },
  borrowBody: {
    th: 'ธนาคารดูว่าคุณผ่อนไหวแค่ไหน จึงให้กู้ได้ไม่เกินรายจ่าย 3 เดือนของคุณ กู้เป็นขั้นละ 10,000 ผ่อนคืนเดือนละ 10% ของยอดที่กู้ ประมาณ 11 เดือนก็หมด',
    en: 'The bank lends against what you can service, so the ceiling is three months of your expenses. Borrow in ฿10,000 steps and repay 10% of the amount drawn each month, clearing in about eleven months.',
  },
  borrowAmount: { th: 'ยอดที่จะกู้', en: 'Amount to borrow' },
  borrowCeiling: { th: 'กู้ได้อีกไม่เกิน', en: 'Still available' },
  borrowMonthly: { th: 'ผ่อนเดือนละ', en: 'Monthly payment' },
  borrowConfirm: { th: 'กู้เลย', en: 'Borrow' },
  borrowJustEnough: { th: 'กู้พอให้กลับเป็นบวก', en: 'Borrow just enough' },
  cancel: { th: 'ยกเลิก', en: 'Cancel' },

  /* animation speed */
  speed: { th: 'ความเร็ว', en: 'Speed' },
  speedNormal: { th: 'ปกติ', en: 'Normal' },
  speedFast: { th: 'เร็ว', en: 'Fast' },
  speedOff: { th: 'ข้าม', en: 'Skip' },

  /* fast track */
  fastTitle: { th: 'ทางด่วน', en: 'The fast track' },
  fastIntro: {
    th: 'คุณออกจากวงล้อแล้ว จากนี้ไม่มีเงินเดือน มีแต่เงินที่ไหลเข้าเอง ภาษีเปลี่ยนไปคิดจากเงินไหลเข้าแทนเงินเดือน ยิ่งพอร์ตโตขึ้นภาษีก็โตตาม ขั้นถัดไปคือสร้างรายได้เพิ่มให้ถึงเป้าด้านล่าง แล้วเก็บเงินไปซื้อความฝันของคุณ',
    en: 'You are off the wheel. No salary from here on, only income that arrives by itself, and the tax line now follows that income instead of a payslip, growing as the portfolio does. Next: build the extra monthly income shown below, then save up for your dream.',
  },
  fastGoalLabel: { th: 'เป้ารายได้เพิ่มต่อเดือน', en: 'Extra monthly income to reach' },
  fastIncome: { th: 'รายได้ทางด่วนต่อเดือน', en: 'Fast-track income' },
  yourDream: { th: 'ความฝันของคุณ', en: 'Your dream' },
  buyDream: { th: 'ซื้อความฝัน', en: 'Buy the dream' },
  dreamsDone: { th: 'ทำสำเร็จแล้ว', en: 'Achieved' },
  pickNextDream: { th: 'ตั้งความฝันข้อต่อไป', en: 'Set your next dream' },
  pickNextDreamBody: { th: 'ความฝันที่ทำไปแล้วไม่ต้องทำซ้ำ เลือกข้อถัดไปที่อยากไล่ตาม จะเลือกของถูกไว้ก่อนแล้วค่อยไต่ขึ้น หรือกระโดดไปข้อที่แพงที่สุดเลยก็ได้', en: 'A dream you have already achieved does not need doing twice. Pick the next one to chase: work up from the cheap end, or jump straight to the most expensive.' },
  swapDream: { th: 'เปลี่ยนความฝัน', en: 'Change dream' },
  dreamCollection: { th: 'ความฝันที่ทำสำเร็จ', en: 'Dreams achieved' },
  allDreamsDone: { th: 'ทำครบทุกข้อแล้ว', en: 'Every dream achieved' },
  notYet: { th: 'ยังไม่ซื้อ', en: 'Not yet' },
  invest: { th: 'ลงทุน', en: 'Invest' },

  /* fast-track deals + legacy */
  chooseFastHint: {
    th: 'ดีลทางด่วนคือของที่คุณซื้อได้เรื่อย ๆ ส่วนดีลระดับนายทุนคือกิจการที่ทั้งจังหวัดใช้บริการ ราคาหลักร้อยล้าน และมีคนได้ประโยชน์จากมันจริง ๆ',
    en: 'A fast-track deal is something you can keep buying. A capitalist deal is the sort of business a whole province uses: hundreds of millions, and real people on the other end of it.',
  },
  fastDealBtn: { th: 'ดีลทางด่วน', en: 'Fast-track deal' },
  megaDealBtn: { th: 'ดีลระดับนายทุน', en: 'Capitalist deal' },
  sellBiz: { th: 'ขายกิจการ', en: 'Sell the business' },
  closeBiz: { th: 'ปิดกิจการ', en: 'Close it down' },
  bizExitNote: { th: 'ขายเองได้ทันทีที่ 18 เท่าของกำไรต่อเดือน ถ้ารอคนซื้อบนช่องตลาดจะได้ 40 ถึง 60 เท่า', en: 'A private sale pays 18x monthly profit today. Waiting for a buyer on a market tile pays 40 to 60x.' },
  growing: { th: 'กำลังโต', en: 'growing' },
  shrinking: { th: 'กำลังแผ่ว', en: 'softening' },
  swingLabel: { th: 'รายได้แกว่งได้ถึง', en: 'Income can swing by' },
  leverageNote: {
    th: 'ดีลนี้กู้ธนาคารมาด้วย หนี้ก้อนนี้จึงติดไปกับตัวสินทรัพย์และโผล่ในงบ ตัวเลขเงินเข้าต่อเดือนหักค่าผ่อนให้แล้ว ยิ่งผ่อนไปเงินต้นยิ่งลด และถ้าปิดหนี้ได้ ค่าผ่อนทั้งก้อนจะกลายเป็นรายได้',
    en: 'This one is bought with a bank loan, so the debt travels with the asset and appears on your statement. The monthly income shown is already net of the payment, the principal falls every month, and clearing the loan turns the whole payment into income.',
  },
  impactLabel: { th: 'คนที่ได้ประโยชน์', en: 'People served' },

  legacyTitle: { th: 'มรดกที่ส่งต่อได้จริง', en: 'What actually gets passed on' },
  legacyBody: {
    th: 'ความฝันทำครบหมดแล้ว เงินยังโตต่อไปได้เรื่อย ๆ แต่คำถามเปลี่ยนไปแล้ว จากจะได้มาเท่าไหร่ เป็นของที่มีจะไปอยู่ที่ไหนต่อ',
    en: 'Every dream is achieved and the money can still grow, but the question has changed: from how much you get, to where any of it ends up.',
  },
  estateTaxDue: { th: 'ภาษีมรดกที่ทายาทจะโดน', en: 'Inheritance tax on your heirs' },
  estateTaxNone: { th: 'ยังไม่ถึงเกณฑ์ 100 ล้าน', en: 'Below the 100m threshold' },
  insuranceCover: { th: 'ทุนประกันชีวิต', en: 'Life cover' },
  donatedTotal: { th: 'บริจาคไปแล้ว', en: 'Given away' },
  optFoundation: { th: 'ตั้งมูลนิธิ', en: 'Endow a foundation' },
  optFoundationBody: {
    th: 'เงินก้อนนี้ออกจากงบของคุณถาวร ไม่มีรายได้กลับมา และไม่มีวันถูกคิดภาษีมรดก เพราะมันไม่ใช่ของคุณแล้ว',
    en: 'This money leaves your balance sheet for good. No income comes back, and it can never be taxed as your estate, because it is no longer yours.',
  },
  optCompany: { th: 'จดนิติบุคคล', en: 'Incorporate' },
  optCompanyBody: {
    th: 'ภาษีเปลี่ยนเป็นอัตราบริษัทแบบคงที่ แต่มีค่าบัญชีรายเดือนที่ต้องจ่ายไม่ว่าจะประหยัดได้หรือไม่ ดูตัวเลขประหยัดต่อเดือนก่อนตัดสินใจ',
    en: 'Tax moves to a flat company rate, against a monthly accounting bill you owe whether it saves anything or not. Check the monthly saving before deciding.',
  },
  optInsurance: { th: 'ทำประกันชีวิตทุนสูง', en: 'Take high life cover' },
  optInsuranceBody: {
    th: 'สินไหมมรณกรรมจ่ายตรงถึงผู้รับผลประโยชน์ จึงไม่ตกเป็นกองมรดกและไม่ถูกคิดภาษี แลกกับเบี้ยที่ต้องจ่ายทุกเดือนไปตลอด',
    en: 'The death benefit is paid straight to the beneficiary, so it never enters the estate and is never taxed. The premium is due every month for the rest of the game.',
  },
  setupCost: { th: 'ค่าจดทะเบียน', en: 'Setup cost' },
  savedPerMonth: { th: 'ประหยัดได้ต่อเดือน', en: 'Saved per month' },
  coverAdded: { th: 'ทุนประกันที่เพิ่ม', en: 'Cover added' },
  premium: { th: 'เบี้ยประกัน', en: 'Premium' },
  alreadyDone: { th: 'ทำแล้ว', en: 'done' },
  accounting: { th: 'ค่าบัญชีบริษัท', en: 'Company accounting' },
  legacyDisclaimer: {
    th: 'ตัวเลขในเกมย่อจากเกณฑ์จริง (ภาษีมรดกเก็บเฉพาะส่วนเกิน 100 ล้าน อัตรา 5% สำหรับลูกหลาน) เพื่อให้เล่นได้ ไม่ใช่คำแนะนำวางแผนภาษี ของจริงต้องคุยกับคนที่มีใบอนุญาต',
    en: 'These figures are simplified from the real thresholds (inheritance tax applies only above 100m, at 5% for direct descendants) so the game can be played. This is not tax advice; for the real thing, talk to someone licensed.',
  },

  /* endings */
  wonTitle: { th: 'คุณหนีออกมาได้แล้ว', en: 'You are out' },
  lostTitle: { th: 'ล้มละลาย', en: 'Bankrupt' },
  lostBody: {
    th: 'เงินสดติดลบจนไม่มีอะไรให้ขายและกู้ไม่ได้อีก ลองใหม่อีกรอบได้เลย รอบหน้าลองปิดหนี้ดอกสูงก่อนสะสมสินทรัพย์',
    en: 'Cash went negative with nothing left to sell and no credit left. Try again, and next time consider clearing the expensive debt before stacking assets.',
  },
  playAgain: { th: 'เล่นอีกรอบ', en: 'Play again' },
  summaryMonths: { th: 'ใช้เวลาไป', en: 'It took' },
  monthsUnit: { th: 'เดือน', en: 'months' },

  /* rules modal */
  rulesGoal: { th: 'เป้าหมาย', en: 'The goal' },
  rulesGoalBody: {
    th: 'คุณเริ่มในวงล้อ ที่ซึ่งรายได้เกือบทั้งหมดมาจากเงินเดือน และหยุดทำงานเมื่อไหร่รายได้ก็หยุดตาม เป้าหมายคือสะสมสินทรัพย์ที่ให้เงินไหลเข้าทุกเดือน จนเงินไหลเข้ามากกว่ารายจ่ายรวม แล้วคุณจะออกจากวงล้อไปสู่ทางด่วน',
    en: 'You start on the wheel, where nearly all income is salary and stops the moment you do. The goal is to stack assets that pay you monthly until that income covers every expense. Then you leave the wheel for the fast track.',
  },
  rulesTurn: { th: 'เล่นยังไง', en: 'How a turn works' },
  rulesTurnBody: {
    th: 'ทอยลูกเต๋าแล้วเดินตามช่อง แต่ละช่องมีเหตุการณ์ของมัน ช่องเงินเดือนจ่ายกระแสเงินสดหนึ่งเดือน (เดินผ่านก็ได้เงิน) ช่องโอกาสให้เลือกดีลเล็กหรือดีลใหญ่ ช่องตลาดคือคนมาขอซื้อของที่คุณถืออยู่ ช่องจิปาถะคือรายจ่ายจรที่โผล่มาตอนไม่ทันตั้งตัว',
    en: 'Roll, move, and resolve the tile you land on. Payday tiles pay one month of cash flow (passing one counts too). Deal tiles let you choose a small or big deal. Market tiles bring buyers for what you hold. Doodad tiles are the unplanned expenses that always arrive at the wrong moment.',
  },
  rulesMoney: { th: 'เรื่องเงินที่ควรรู้', en: 'The money rules' },
  rulesMoneyBody: {
    th: 'อสังหาฯ ใช้เงินดาวน์ไม่กี่เปอร์เซ็นต์ แต่หนี้ที่เหลือติดไปกับตัวสินทรัพย์ ตัวเลข "เงินเข้าต่อเดือน" บนการ์ดจึงหักค่าผ่อนให้แล้ว และทุกเดือนที่ผ่านไป ค่าผ่อนจะกินเงินต้นลงเรื่อย ๆ พอผ่อนหมด ค่าผ่อนก้อนนั้นจะกลายเป็นรายได้ของคุณเต็ม ๆ หุ้นไม่ให้เงินไหลเข้า (ยกเว้นตัวที่ระบุปันผล) กำไรมาจากขายตอนราคาขึ้นเท่านั้น ส่วนเงินกู้ฉุกเฉินกู้ได้ไม่เกินรายจ่าย 3 เดือน ผ่อนคืนเดือนละ 10% ของยอดที่กู้ ราว 11 เดือนก็หมด แต่ระหว่างนั้นกระแสเงินสดจะฝืดมาก',
    en: 'Property takes only a small down payment, and the remaining loan travels with the asset, so the “monthly income” printed on a card is already net of the mortgage. Every month that payment also chips away at the principal, and once the loan is gone the whole payment becomes yours. Shares pay nothing unless a dividend is stated; their profit comes only from selling higher. The emergency loan is capped at three months of expenses and repaid at 10% of the amount drawn each month, clearing in about eleven months, but cash is very tight until it does.',
  },
  rulesTiers: { th: 'ระดับนักลงทุน กับน้ำใจ', en: 'Investor tiers, and generosity' },
  rulesTiersBody: {
    th: 'ป้ายใต้ชื่อเกมคือระดับนักลงทุนของคุณ ไล่จากมนุษย์เงินเดือน ไปมือใหม่หัดลงทุน คนที่หนีออกมาได้ เจ้าของพอร์ต นักลงทุนอาชีพ และนายทุนเป็นขั้นสูงสุด ไม่มีอะไรจบเกมนอกจากล้มละลาย อยากเล่นต่อไปเรื่อย ๆ ก็ได้ อยากหยุดดูสรุปเมื่อไหร่ก็กดปุ่มจบเกมเอง ส่วน "น้ำใจ" ขึ้นเมื่อคุณรับการ์ดที่มีคนอื่นเกี่ยวข้อง เช่นให้ญาติยืมเงินหรือไปทริปกับเพื่อน และลดลงเมื่อปฏิเสธ ถ้าน้ำใจถึง 3 แล้วเงินสดติดลบ จะมีเพื่อนโอนเงินมาให้ก้อนหนึ่งโดยไม่คิดดอกเบี้ย ครั้งเดียวต่อเกม',
    en: 'The badge under the title is your investor tier: salary earner, first-time investor, off the wheel, debt-free owner, professional investor, and capitalist at the top. Nothing ends the game except bankruptcy, so play on as long as you like, or press the end button whenever you want the summary. Generosity rises when you accept a card that involves other people, such as lending to a relative or joining a trip, and falls when you decline. Reach 3 and go cash-negative, and a friend sends money over with no interest, once per game.',
  },
  rulesNote: { th: 'ที่มา', en: 'About this game' },
  rulesNoteBody: {
    th: 'เกมนี้เขียนขึ้นใหม่ทั้งหมดสำหรับเว็บนี้ ทั้งอาชีพ การ์ด ตัวเลข และถ้อยคำ ไม่ได้เกี่ยวข้องกับหรือได้รับอนุญาตจากเจ้าของเกมการเงินเชิงพาณิชย์รายใด กลไกพื้นฐานอย่างงบการเงินส่วนบุคคลและการวัดอิสรภาพจากเงินไหลเข้า เป็นแนวคิดสาธารณะที่ใครก็หยิบมาออกแบบเกมของตัวเองได้',
    en: 'Every profession, card, number and line of text here was written for this site. It is not affiliated with, or licensed by, any commercial financial board game. The underlying ideas, a personal income statement and measuring freedom by passive income, are public concepts anyone may build a game around.',
  },
} satisfies Record<string, Loc>;

export type UIKey = keyof typeof UI;

/**
 * Cut-down tile names. A 7-column ring gives each tile about 40px on a phone,
 * so nothing here goes past five characters; the full name of the tile the
 * player is standing on is spelled out in the middle of the board, and every
 * tile carries the long name in its aria-label.
 */
export const TILE_SHORT = {
  payday: { th: 'เงิน', en: 'Pay' },
  deal: { th: 'โอกาส', en: 'Deal' },
  market: { th: 'ตลาด', en: 'Mkt' },
  doodad: { th: 'จ่าย', en: 'Cost' },
  baby: { th: 'ลูก', en: 'Baby' },
  downsized: { th: 'ตกงาน', en: 'Fired' },
  charity: { th: 'บุญ', en: 'Give' },
  fastpay: { th: 'เงิน', en: 'Pay' },
  fastdeal: { th: 'ดีล', en: 'Deal' },
  fastmarket: { th: 'ตลาด', en: 'Mkt' },
  dream: { th: 'ฝัน', en: 'Dream' },
  bonus: { th: 'โชค', en: 'Luck' },
  setback: { th: 'สะดุด', en: 'Hit' },
} satisfies Record<string, Loc>;
